var QUESTIONS = [
  // MUSIC - MTV Era, Pop Stars, Rock, New Wave
  { category: "Music", question: "What year did MTV first launch?", answers: ["1979", "1981", "1983", "1985"], correct: 1 },
  { category: "Music", question: "What was the first music video played on MTV?", answers: ["Video Killed the Radio Star", "Thriller", "Like a Virgin", "Sweet Child O' Mine"], correct: 0 },
  { category: "Music", question: "Which Michael Jackson album became the best-selling album of all time?", answers: ["Bad", "Dangerous", "Thriller", "Off the Wall"], correct: 2 },
  { category: "Music", question: "What year was Michael Jackson's 'Thriller' music video released?", answers: ["1982", "1983", "1984", "1985"], correct: 1 },
  { category: "Music", question: "What was Madonna's first top 10 hit in the US?", answers: ["Like a Virgin", "Holiday", "Borderline", "Material Girl"], correct: 2 },
  { category: "Music", question: "Which band released 'Sweet Child O' Mine' in 1987?", answers: ["Bon Jovi", "Guns N' Roses", "Motley Crue", "Def Leppard"], correct: 1 },
  { category: "Music", question: "What was Prince's biggest hit song from the 1980s?", answers: ["1999", "Purple Rain", "When Doves Cry", "Kiss"], correct: 2 },
  { category: "Music", question: "Which female artist sang 'What's Love Got to Do with It'?", answers: ["Whitney Houston", "Cyndi Lauper", "Tina Turner", "Pat Benatar"], correct: 2 },
  { category: "Music", question: "What band did George Michael belong to before going solo?", answers: ["Duran Duran", "Wham!", "Culture Club", "The Police"], correct: 1 },
  { category: "Music", question: "Which artist released the album 'Purple Rain' in 1984?", answers: ["Prince", "Michael Jackson", "David Bowie", "Billy Idol"], correct: 0 },
  { category: "Music", question: "What was Bon Jovi's signature song from 1986?", answers: ["You Give Love a Bad Name", "Livin' on a Prayer", "Wanted Dead or Alive", "Bad Medicine"], correct: 1 },
  { category: "Music", question: "Which band sang 'Don't You (Forget About Me)' featured in The Breakfast Club?", answers: ["Simple Minds", "Tears for Fears", "A-ha", "Depeche Mode"], correct: 0 },
  { category: "Music", question: "What was Whitney Houston's first #1 hit?", answers: ["How Will I Know", "Saving All My Love for You", "Greatest Love of All", "I Wanna Dance with Somebody"], correct: 1 },
  { category: "Music", question: "Which Irish band released 'With or Without You' in 1987?", answers: ["The Cure", "U2", "R.E.M.", "INXS"], correct: 1 },
  { category: "Music", question: "What was the name of the charity supergroup that recorded 'We Are the World'?", answers: ["Band Aid", "USA for Africa", "Live Aid", "Hear 'n Aid"], correct: 1 },
  { category: "Music", question: "Which synth-pop band had a hit with 'Take On Me'?", answers: ["Depeche Mode", "Pet Shop Boys", "A-ha", "Erasure"], correct: 2 },
  { category: "Music", question: "What was Bruce Springsteen's biggest album of the 1980s?", answers: ["The River", "Nebraska", "Born in the U.S.A.", "Tunnel of Love"], correct: 2 },
  { category: "Music", question: "Which band released 'Every Breath You Take' in 1983?", answers: ["The Police", "Duran Duran", "The Clash", "The Cure"], correct: 0 },
  { category: "Music", question: "What color rain did Prince sing about?", answers: ["Purple", "Red", "Blue", "Black"], correct: 0 },
  { category: "Music", question: "Which female artist sang 'Girls Just Want to Have Fun'?", answers: ["Madonna", "Cyndi Lauper", "Joan Jett", "Pat Benatar"], correct: 1 },
  { category: "Music", question: "What was the name of Run-DMC's collaboration with Aerosmith?", answers: ["Walk This Way", "My Adidas", "It's Tricky", "Rock Box"], correct: 0 },
  { category: "Music", question: "Which band had a hit with 'Hungry Like the Wolf'?", answers: ["Spandau Ballet", "Duran Duran", "Culture Club", "Adam and the Ants"], correct: 1 },
  { category: "Music", question: "What was Rick Astley's breakout hit in 1987?", answers: ["Together Forever", "Never Gonna Give You Up", "Whenever You Need Somebody", "She Wants to Dance with Me"], correct: 1 },
  { category: "Music", question: "Which hair metal band released 'Pour Some Sugar on Me'?", answers: ["Poison", "Motley Crue", "Def Leppard", "Warrant"], correct: 2 },
  { category: "Music", question: "What was the name of the all-female rock band featuring Joan Jett?", answers: ["The Bangles", "The Go-Go's", "The Runaways", "Heart"], correct: 2 },
  { category: "Music", question: "Which artist released 'Livin' on a Prayer'?", answers: ["Van Halen", "Bon Jovi", "Journey", "Foreigner"], correct: 1 },
  { category: "Music", question: "What was Michael Jackson's follow-up album to 'Thriller'?", answers: ["Dangerous", "Bad", "History", "Invincible"], correct: 1 },
  { category: "Music", question: "Which band sang 'Sweet Dreams (Are Made of This)'?", answers: ["Eurythmics", "Blondie", "Berlin", "The Human League"], correct: 0 },
  { category: "Music", question: "What was the name of the lead singer of Culture Club?", answers: ["Adam Ant", "Boy George", "Morrissey", "Robert Smith"], correct: 1 },
  { category: "Music", question: "Which band released the album 'Appetite for Destruction'?", answers: ["Motley Crue", "Guns N' Roses", "Skid Row", "Poison"], correct: 1 },

  // MOVIES - Blockbusters, Classics, Icons
  { category: "Movies", question: "What year was E.T. the Extra-Terrestrial released?", answers: ["1980", "1981", "1982", "1983"], correct: 2 },
  { category: "Movies", question: "In Back to the Future, what speed must the DeLorean reach to time travel?", answers: ["77 mph", "88 mph", "99 mph", "100 mph"], correct: 1 },
  { category: "Movies", question: "Who played Indiana Jones in Raiders of the Lost Ark?", answers: ["Tom Selleck", "Harrison Ford", "Kurt Russell", "Jeff Bridges"], correct: 1 },
  { category: "Movies", question: "What was the highest-grossing film of the 1980s?", answers: ["Star Wars: Return of the Jedi", "E.T.", "Back to the Future", "Ghostbusters"], correct: 1 },
  { category: "Movies", question: "Who directed The Breakfast Club?", answers: ["John Hughes", "Steven Spielberg", "Robert Zemeckis", "James Cameron"], correct: 0 },
  { category: "Movies", question: "What year was the first Star Wars sequel, The Empire Strikes Back, released?", answers: ["1980", "1981", "1982", "1983"], correct: 0 },
  { category: "Movies", question: "In The Karate Kid, what is Mr. Miyagi's first name?", answers: ["Keisuke", "Nariyoshi", "Hideo", "Kesuke"], correct: 1 },
  { category: "Movies", question: "What was the tagline for Ghostbusters?", answers: ["Who you gonna call?", "We ain't afraid of no ghost", "Bustin' makes me feel good", "Back off, man. I'm a scientist"], correct: 0 },
  { category: "Movies", question: "Which 1984 film featured the phrase 'I'll be back'?", answers: ["RoboCop", "Predator", "The Terminator", "Commando"], correct: 2 },
  { category: "Movies", question: "What is the name of the island in Jurassic Park? (Though released in 1993, based on 1980s book)", answers: ["Isla Sorna", "Isla Nublar", "Isla Muerta", "Isla Pena"], correct: 1 },
  { category: "Movies", question: "In Ferris Bueller's Day Off, what kind of car do they 'borrow'?", answers: ["Porsche 911", "Ferrari 250 GT", "Corvette Stingray", "Jaguar E-Type"], correct: 1 },
  { category: "Movies", question: "What year did the first Indiana Jones movie premiere?", answers: ["1980", "1981", "1982", "1983"], correct: 1 },
  { category: "Movies", question: "Who played Marty McFly in Back to the Future?", answers: ["Eric Stoltz", "Michael J. Fox", "C. Thomas Howell", "Emilio Estevez"], correct: 1 },
  { category: "Movies", question: "What was the name of the computer in WarGames?", answers: ["HAL 9000", "WOPR", "Skynet", "Mother"], correct: 1 },
  { category: "Movies", question: "Which 1987 film featured the quote 'Nobody puts Baby in a corner'?", answers: ["Flashdance", "Footloose", "Dirty Dancing", "Girls Just Want to Have Fun"], correct: 2 },
  { category: "Movies", question: "What was the name of Eddie Murphy's character in Beverly Hills Cop?", answers: ["Billy Rosewood", "Axel Foley", "Reggie Hammond", "Marcus Burnett"], correct: 1 },
  { category: "Movies", question: "In Gremlins, what are the three rules for taking care of Mogwai?", answers: ["No water, no food after midnight, no bright light", "No water, no bright light, no loud noises", "No water after midnight, no bright light, no feeding after midnight", "No bright light, no water, no feeding after midnight"], correct: 3 },
  { category: "Movies", question: "What actor played the lead role in Die Hard?", answers: ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Kurt Russell"], correct: 2 },
  { category: "Movies", question: "What building does Die Hard take place in?", answers: ["Empire State Building", "Nakatomi Plaza", "Chrysler Building", "Willis Tower"], correct: 1 },
  { category: "Movies", question: "Which Spielberg movie featured a boy and his alien friend?", answers: ["Close Encounters", "E.T.", "Batteries Not Included", "Cocoon"], correct: 1 },
  { category: "Movies", question: "What color are the Ghostbusters' uniforms?", answers: ["Grey", "Blue", "Tan/Khaki", "Black"], correct: 2 },
  { category: "Movies", question: "In Top Gun, what is Maverick's real name?", answers: ["Pete Mitchell", "Tom Kazansky", "Nick Bradshaw", "Rick Heatherly"], correct: 0 },
  { category: "Movies", question: "What 1986 film was advertised with 'Be afraid. Be very afraid'?", answers: ["Aliens", "The Fly", "The Thing", "Poltergeist"], correct: 1 },
  { category: "Movies", question: "Who directed Aliens (1986)?", answers: ["Ridley Scott", "James Cameron", "John Carpenter", "David Cronenberg"], correct: 1 },
  { category: "Movies", question: "What year was The Shining released?", answers: ["1980", "1981", "1982", "1983"], correct: 0 },
  { category: "Movies", question: "In Beetlejuice, how many times must you say his name to summon him?", answers: ["Once", "Twice", "Three times", "Four times"], correct: 2 },
  { category: "Movies", question: "What was Tom Cruise's character's nickname in Top Gun?", answers: ["Iceman", "Goose", "Maverick", "Viper"], correct: 2 },
  { category: "Movies", question: "Which 1985 film featured a group of kids searching for pirate treasure?", answers: ["The Goonies", "Stand By Me", "The Lost Boys", "Monster Squad"], correct: 0 },
  { category: "Movies", question: "What was the name of the department store in Mannequin?", answers: ["Prince & Company", "Illustra", "Wanamaker's", "Macy's"], correct: 0 },
  { category: "Movies", question: "In Rain Man, what airline does Raymond say never crashes?", answers: ["United", "American", "Delta", "Qantas"], correct: 3 },

  // TV SHOWS - Sitcoms, Dramas, Cartoons
  { category: "TV Shows", question: "What was the name of the bar in Cheers?", answers: ["MacLaren's", "Cheers", "Paddy's Pub", "The Regal Beagle"], correct: 1 },
  { category: "TV Shows", question: "What year did The Simpsons first appear as shorts on The Tracey Ullman Show?", answers: ["1985", "1987", "1988", "1989"], correct: 1 },
  { category: "TV Shows", question: "Who shot J.R. in Dallas?", answers: ["Sue Ellen", "Kristin Shepard", "Cliff Barnes", "Bobby Ewing"], correct: 1 },
  { category: "TV Shows", question: "What was the name of the A-Team's leader?", answers: ["Hannibal", "Face", "B.A.", "Murdock"], correct: 0 },
  { category: "TV Shows", question: "In Knight Rider, what was the name of Michael Knight's car?", answers: ["KARR", "KITT", "KATT", "KIRT"], correct: 1 },
  { category: "TV Shows", question: "What was ALF's real name on his home planet?", answers: ["Gordon Shumway", "Willie Tanner", "Brian Shumway", "Max Wright"], correct: 0 },
  { category: "TV Shows", question: "Which Golden Girls character was from St. Olaf?", answers: ["Dorothy", "Blanche", "Rose", "Sophia"], correct: 2 },
  { category: "TV Shows", question: "What was the name of the Tanner family's alien houseguest?", answers: ["Mork", "ALF", "Alf", "Gordon"], correct: 1 },
  { category: "TV Shows", question: "In Family Ties, what was Alex P. Keaton's middle initial stand for?", answers: ["Paul", "Peter", "Patrick", "Preston"], correct: 3 },
  { category: "TV Shows", question: "What was Magnum P.I.'s first name?", answers: ["Thomas", "Jonathan", "Theodore", "Timothy"], correct: 0 },
  { category: "TV Shows", question: "Which Cosby Show character was played by Lisa Bonet?", answers: ["Rudy", "Vanessa", "Denise", "Sondra"], correct: 2 },
  { category: "TV Shows", question: "What was the name of the town in Twin Peaks? (premiered 1990 but close enough)", answers: ["Twin Peaks", "Paradise", "Wayward Pines", "Evergreen"], correct: 0 },
  { category: "TV Shows", question: "In Miami Vice, what color was Crockett's Ferrari?", answers: ["Red", "Black", "White", "Yellow"], correct: 2 },
  { category: "TV Shows", question: "What was MacGyver's first name?", answers: ["Angus", "Richard", "Jack", "Never revealed"], correct: 0 },
  { category: "TV Shows", question: "Which 1980s cartoon featured 'Transformers, more than meets the eye'?", answers: ["G.I. Joe", "Transformers", "He-Man", "ThunderCats"], correct: 1 },
  { category: "TV Shows", question: "What was the name of He-Man's alter ego?", answers: ["Adam", "Adora", "Duncan", "Randor"], correct: 0 },
  { category: "TV Shows", question: "In ThunderCats, what was Lion-O's weapon called?", answers: ["Thunder Sword", "Sword of Omens", "Claw Shield", "Power Blade"], correct: 1 },
  { category: "TV Shows", question: "What planet was Mork from in Mork & Mindy?", answers: ["Mars", "Ork", "Pluto", "Zebulon"], correct: 1 },
  { category: "TV Shows", question: "What was the name of the spaceship in Battlestar Galactica?", answers: ["Galactica", "Enterprise", "Pegasus", "Voyager"], correct: 0 },
  { category: "TV Shows", question: "In Diff'rent Strokes, what was the catchphrase 'Whatchu talkin' bout' followed by?", answers: ["Philip", "Willis", "Arnold", "Willis"], correct: 3 },
  { category: "TV Shows", question: "What was the Dukes of Hazzard's car called?", answers: ["The General Lee", "The Duke", "The Rebel", "The Confederate"], correct: 0 },
  { category: "TV Shows", question: "Which TV show featured the Keatons family?", answers: ["Growing Pains", "Family Ties", "The Cosby Show", "Who's the Boss?"], correct: 1 },
  { category: "TV Shows", question: "What was the name of the boss in Who's the Boss?", answers: ["Angela", "Samantha", "Mona", "Tony"], correct: 0 },
  { category: "TV Shows", question: "In Quantum Leap, who was Sam's holographic companion?", answers: ["Al", "Ziggy", "Gooshie", "Sam"], correct: 0 },
  { category: "TV Shows", question: "What was the name of the helicopter in Airwolf?", answers: ["Blue Thunder", "Airwolf", "Stringfellow", "The Lady"], correct: 1 },
  { category: "TV Shows", question: "Which show featured detectives Cagney and Lacey?", answers: ["Hill Street Blues", "Cagney & Lacey", "Hunter", "21 Jump Street"], correct: 1 },
  { category: "TV Shows", question: "What was the name of Punky Brewster's dog?", answers: ["Rufus", "Brandon", "Chester", "Lucky"], correct: 1 },
  { category: "TV Shows", question: "In Growing Pains, what was Dr. Jason Seaver's profession?", answers: ["Lawyer", "Psychiatrist", "Teacher", "Doctor"], correct: 1 },
  { category: "TV Shows", question: "What was the name of the robot in Small Wonder?", answers: ["Vicki", "Jamie", "Harriet", "Joan"], correct: 0 },
  { category: "TV Shows", question: "Which show featured teenagers at Bayside High School?", answers: ["The Fresh Prince", "Saved by the Bell", "Head of the Class", "Parker Lewis Can't Lose"], correct: 1 },

  // VIDEO GAMES - Nintendo, Arcade, Console Wars
  { category: "Video Games", question: "What year was the Nintendo Entertainment System released in North America?", answers: ["1983", "1985", "1987", "1989"], correct: 1 },
  { category: "Video Games", question: "What was Mario's original name in Donkey Kong?", answers: ["Luigi", "Jumpman", "Mario", "Mr. Video"], correct: 1 },
  { category: "Video Games", question: "What is the name of Pac-Man's wife?", answers: ["Mrs. Pac-Man", "Lady Pac-Man", "Pac-Woman", "Pinky"], correct: 0 },
  { category: "Video Games", question: "What year was Pac-Man released?", answers: ["1978", "1980", "1982", "1984"], correct: 1 },
  { category: "Video Games", question: "In what year did the video game crash occur in North America?", answers: ["1981", "1983", "1985", "1987"], correct: 1 },
  { category: "Video Games", question: "What was the first game released for the NES in North America?", answers: ["Super Mario Bros.", "Duck Hunt", "Donkey Kong", "Excitebike"], correct: 0 },
  { category: "Video Games", question: "What was Link's sword called in The Legend of Zelda?", answers: ["Excalibur", "Master Sword", "Wooden Sword", "Kokiri Sword"], correct: 1 },
  { category: "Video Games", question: "Who is the main antagonist in the Super Mario series?", answers: ["Wario", "Bowser", "Donkey Kong", "King Koopa"], correct: 1 },
  { category: "Video Games", question: "What company created Sonic the Hedgehog?", answers: ["Nintendo", "Sega", "Atari", "Capcom"], correct: 1 },
  { category: "Video Games", question: "What was the best-selling game on the original Game Boy?", answers: ["Super Mario Land", "Pokemon Red/Blue", "Tetris", "The Legend of Zelda: Link's Awakening"], correct: 2 },
  { category: "Video Games", question: "In Donkey Kong, what is the name of the damsel in distress?", answers: ["Princess Peach", "Pauline", "Princess Daisy", "Lady"], correct: 1 },
  { category: "Video Games", question: "What year was Tetris released?", answers: ["1984", "1985", "1986", "1987"], correct: 0 },
  { category: "Video Games", question: "What was the first home console to have CD-ROM support?", answers: ["Sega CD", "PlayStation", "TurboGrafx-CD", "3DO"], correct: 2 },
  { category: "Video Games", question: "What color is Pac-Man?", answers: ["Red", "Yellow", "Orange", "Green"], correct: 1 },
  { category: "Video Games", question: "In Street Fighter II, which country is Ryu from?", answers: ["China", "Japan", "Korea", "Thailand"], correct: 1 },
  { category: "Video Games", question: "What was the name of the duck-hunting accessory for NES?", answers: ["Power Gun", "Zapper", "Light Blaster", "Nintendo Gun"], correct: 1 },
  { category: "Video Games", question: "What year was the Sega Genesis released in North America?", answers: ["1987", "1988", "1989", "1990"], correct: 2 },
  { category: "Video Games", question: "What was the maximum number of lives you could have in Super Mario Bros.?", answers: ["99", "100", "128", "255"], correct: 0 },
  { category: "Video Games", question: "Who created Pac-Man?", answers: ["Shigeru Miyamoto", "Toru Iwatani", "Gunpei Yokoi", "Satoshi Tajiri"], correct: 1 },
  { category: "Video Games", question: "What was the name of Mike Tyson's opponent in Mike Tyson's Punch-Out!!?", answers: ["Glass Joe", "King Hippo", "Mr. Dream", "Little Mac"], correct: 3 },
  { category: "Video Games", question: "In what year was the Game Boy released in North America?", answers: ["1987", "1988", "1989", "1990"], correct: 2 },
  { category: "Video Games", question: "What was the first arcade game to feature true stereo sound?", answers: ["Donkey Kong", "Pac-Man", "Space Invaders", "Centipede"], correct: 0 },
  { category: "Video Games", question: "What was the name of the princess in the original Legend of Zelda?", answers: ["Princess Toadstool", "Princess Zelda", "Princess Daisy", "Princess Peach"], correct: 1 },
  { category: "Video Games", question: "Which game featured the Konami Code?", answers: ["Contra", "Castlevania", "Gradius", "All of the above"], correct: 3 },
  { category: "Video Games", question: "What was the Konami Code sequence?", answers: ["Up Up Down Down Left Right Left Right B A", "Down Down Up Up Right Left Right Left A B", "Up Down Left Right A B Start", "Left Right Up Down B A B A"], correct: 0 },
  { category: "Video Games", question: "What year was Super Mario Bros. 3 released in North America?", answers: ["1988", "1989", "1990", "1991"], correct: 2 },
  { category: "Video Games", question: "What was the name of Donkey Kong's nephew?", answers: ["Diddy Kong", "Diddy", "Donkey Kong Jr.", "Chunky Kong"], correct: 2 },
  { category: "Video Games", question: "What was the first game to feature Mario's brother Luigi?", answers: ["Donkey Kong", "Mario Bros.", "Super Mario Bros.", "Wrecking Crew"], correct: 1 },
  { category: "Video Games", question: "In Mega Man, what is Dr. Wily's first name?", answers: ["Albert", "Thomas", "William", "Henry"], correct: 0 },
  { category: "Video Games", question: "What was the name of the final level in the original Donkey Kong?", answers: ["75m", "100m", "125m", "50m"], correct: 1 },

  // FASHION - Trends, Styles, Icons
  { category: "Fashion", question: "What accessory was Madonna famous for wearing in the 1980s?", answers: ["Leg warmers", "Fingerless gloves", "Scrunchies", "Fanny packs"], correct: 1 },
  { category: "Fashion", question: "What type of pants were popular in the 1980s with a tapered leg?", answers: ["Bell-bottoms", "Parachute pants", "Cargo pants", "Capris"], correct: 1 },
  { category: "Fashion", question: "What brand of jeans was most popular in the 1980s?", answers: ["Levi's", "Calvin Klein", "Jordache", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What hairstyle was characterized by short on top and long in the back?", answers: ["Mullet", "Jheri curl", "Afro", "Bowl cut"], correct: 0 },
  { category: "Fashion", question: "What exercise clothing item became a fashion statement?", answers: ["Yoga pants", "Leg warmers", "Sports bras", "Compression shorts"], correct: 1 },
  { category: "Fashion", question: "What were the padded inserts in jackets called?", answers: ["Shoulder lifts", "Power shoulders", "Shoulder pads", "Jacket pads"], correct: 2 },
  { category: "Fashion", question: "What material were many 1980s jackets made from?", answers: ["Leather", "Denim", "Neon spandex", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What brand created the iconic white sneakers with three stripes?", answers: ["Nike", "Reebok", "Adidas", "Puma"], correct: 2 },
  { category: "Fashion", question: "What was the popular hairstyle that required lots of hairspray?", answers: ["The Rachel", "Big hair", "The Bob", "Pixie cut"], correct: 1 },
  { category: "Fashion", question: "What accessory did people wear on their heads while exercising?", answers: ["Bandanas", "Headbands", "Sweatbands", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What pattern was popular on sweaters in the 1980s?", answers: ["Argyle", "Geometric", "Animal print", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What type of jacket did Michael Jackson famously wear?", answers: ["Bomber jacket", "Red leather jacket", "Denim jacket", "Varsity jacket"], correct: 1 },
  { category: "Fashion", question: "What were the colorful, plastic bracelets called?", answers: ["Friendship bracelets", "Jelly bracelets", "Rubber bands", "Snap bracelets"], correct: 1 },
  { category: "Fashion", question: "What shoe brand became popular with the rise of hip-hop?", answers: ["Converse", "Adidas", "Reebok", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What was the name of the bright, neon-colored clothing trend?", answers: ["Day-Glo", "Fluorescent fashion", "Neon wear", "Bright trend"], correct: 0 },
  { category: "Fashion", question: "What type of socks were worn with sneakers?", answers: ["Ankle socks", "Tube socks", "No-show socks", "Knee-high socks"], correct: 1 },
  { category: "Fashion", question: "What was the popular acid-washed clothing item?", answers: ["Shirts", "Jeans", "Jackets", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What accessory did people wear multiple of on one wrist?", answers: ["Watches", "Bracelets", "Sweatbands", "Scrunchies"], correct: 1 },
  { category: "Fashion", question: "What fabric was used for tracksuits and windbreakers?", answers: ["Cotton", "Polyester", "Nylon", "Spandex"], correct: 2 },
  { category: "Fashion", question: "What footwear was popularized by the movie Flashdance?", answers: ["High heels", "Leg warmers over boots", "Ballet flats", "Combat boots"], correct: 1 },

  // TECHNOLOGY - Computers, Gadgets, Innovation
  { category: "Technology", question: "What year was the Apple Macintosh released?", answers: ["1982", "1984", "1986", "1988"], correct: 1 },
  { category: "Technology", question: "What was the name of IBM's first personal computer?", answers: ["IBM PC", "IBM XT", "IBM AT", "IBM PS/2"], correct: 0 },
  { category: "Technology", question: "What portable music player did Sony introduce in 1979 that dominated the 1980s?", answers: ["Discman", "Walkman", "Soundman", "Tape Master"], correct: 1 },
  { category: "Technology", question: "What year was Microsoft Windows 1.0 released?", answers: ["1983", "1985", "1987", "1989"], correct: 1 },
  { category: "Technology", question: "What was the storage capacity of a standard 3.5-inch floppy disk?", answers: ["720 KB or 1.44 MB", "1 MB", "2 MB", "5 MB"], correct: 0 },
  { category: "Technology", question: "What was the name of Apple's failed computer from 1983?", answers: ["Apple IIe", "Lisa", "Macintosh", "Newton"], correct: 1 },
  { category: "Technology", question: "What video format won the war against Betamax?", answers: ["VHS", "LaserDisc", "Video 2000", "CED"], correct: 0 },
  { category: "Technology", question: "What company created the Commodore 64?", answers: ["IBM", "Commodore International", "Atari", "Apple"], correct: 1 },
  { category: "Technology", question: "What was the first commercially available cell phone?", answers: ["Nokia 1011", "Motorola DynaTAC", "Ericsson Hotline", "IBM Simon"], correct: 1 },
  { category: "Technology", question: "What year was the CD (Compact Disc) introduced?", answers: ["1980", "1982", "1984", "1986"], correct: 1 },
  { category: "Technology", question: "What was the original price of the Motorola DynaTAC cell phone?", answers: ["$1,995", "$2,995", "$3,995", "$4,995"], correct: 2 },
  { category: "Technology", question: "What computer was advertised during the 1984 Super Bowl?", answers: ["IBM PC", "Apple Macintosh", "Commodore 64", "Atari ST"], correct: 1 },
  { category: "Technology", question: "What was the name of the first spreadsheet program?", answers: ["Excel", "Lotus 1-2-3", "VisiCalc", "Quattro Pro"], correct: 2 },
  { category: "Technology", question: "What year was the first email sent?", answers: ["1971", "1981", "1985", "1989"], correct: 0 },
  { category: "Technology", question: "What was the Commodore 64's retail price at launch?", answers: ["$395", "$495", "$595", "$695"], correct: 2 },
  { category: "Technology", question: "What technology allowed computers to connect via phone lines?", answers: ["Router", "Modem", "Hub", "Switch"], correct: 1 },
  { category: "Technology", question: "What was the baud rate of early modems in the 1980s?", answers: ["300-1200 baud", "2400-9600 baud", "14.4k baud", "56k baud"], correct: 0 },
  { category: "Technology", question: "What gaming console did Atari release in 1977 that dominated the early 80s?", answers: ["Atari 5200", "Atari 2600", "Atari 7800", "Atari Jaguar"], correct: 1 },
  { category: "Technology", question: "What was the first laptop computer?", answers: ["Compaq Portable", "Osborne 1", "Grid Compass", "IBM PC Convertible"], correct: 1 },
  { category: "Technology", question: "What year was the World Wide Web invented? (late 80s)", answers: ["1985", "1987", "1989", "1991"], correct: 2 },
  { category: "Technology", question: "What was the first commercially successful graphical user interface?", answers: ["Windows 1.0", "Apple Macintosh", "Xerox Star", "Amiga Workbench"], correct: 1 },
  { category: "Technology", question: "What video game console was released by Sega in 1988?", answers: ["Sega Master System", "Sega Genesis", "Sega Saturn", "Sega Dreamcast"], correct: 1 },
  { category: "Technology", question: "What was the name of the first computer virus?", answers: ["ILOVEYOU", "Melissa", "Brain", "Morris Worm"], correct: 2 },
  { category: "Technology", question: "What electronic organizer was popular in the 1980s?", answers: ["Palm Pilot", "Filofax", "Rolodex", "DayTimer"], correct: 1 },
  { category: "Technology", question: "What was the first computer to use a mouse?", answers: ["Apple Macintosh", "Xerox Alto", "Apple Lisa", "Commodore Amiga"], correct: 1 },
  { category: "Technology", question: "What year was the first domain name registered?", answers: ["1983", "1985", "1987", "1989"], correct: 1 },
  { category: "Technology", question: "What was the name of Nintendo's robot accessory?", answers: ["ROB (R.O.B.)", "ROBO", "Nintendo Bot", "Game Robot"], correct: 0 },
  { category: "Technology", question: "What technology allowed home recording of TV shows?", answers: ["DVR", "TiVo", "VCR", "Betamax"], correct: 2 },
  { category: "Technology", question: "What was the first commercially available digital camera?", answers: ["Sony Mavica", "Kodak DCS", "Canon RC-701", "Fuji DS-1P"], correct: 0 },
  { category: "Technology", question: "What home computer was known for its sound and graphics capabilities?", answers: ["Commodore 64", "Amiga", "Atari ST", "All of the above"], correct: 3 },

  // SPORTS - Athletes, Events, Championships
  { category: "Sports", question: "Who won the most Super Bowls in the 1980s?", answers: ["Dallas Cowboys", "San Francisco 49ers", "Miami Dolphins", "Washington Redskins"], correct: 1 },
  { category: "Sports", question: "What NBA team won the most championships in the 1980s?", answers: ["Boston Celtics", "Los Angeles Lakers", "Detroit Pistons", "Philadelphia 76ers"], correct: 1 },
  { category: "Sports", question: "Who was known as 'The Great One' in hockey?", answers: ["Mario Lemieux", "Bobby Orr", "Wayne Gretzky", "Gordie Howe"], correct: 2 },
  { category: "Sports", question: "What year did the Miracle on Ice occur at the Winter Olympics?", answers: ["1980", "1982", "1984", "1988"], correct: 0 },
  { category: "Sports", question: "Who won the boxing match between Sugar Ray Leonard and Marvin Hagler in 1987?", answers: ["Sugar Ray Leonard", "Marvin Hagler", "Draw", "No contest"], correct: 0 },
  { category: "Sports", question: "What track star won four gold medals at the 1984 Olympics?", answers: ["Jesse Owens", "Carl Lewis", "Edwin Moses", "Michael Johnson"], correct: 1 },
  { category: "Sports", question: "Who was the youngest heavyweight boxing champion in history (1986)?", answers: ["Muhammad Ali", "Mike Tyson", "George Foreman", "Evander Holyfield"], correct: 1 },
  { category: "Sports", question: "What city hosted the 1984 Summer Olympics?", answers: ["Seoul", "Moscow", "Los Angeles", "Atlanta"], correct: 2 },
  { category: "Sports", question: "Who was the NBA Finals MVP in 1980 as a rookie?", answers: ["Larry Bird", "Magic Johnson", "Kareem Abdul-Jabbar", "Julius Erving"], correct: 1 },
  { category: "Sports", question: "What baseball player broke the single-season home run record in 1987?", answers: ["Mark McGwire", "Jose Canseco", "Roger Maris", "None, record stood"], correct: 3 },
  { category: "Sports", question: "Who won the World Series in 1986, breaking an 86-year drought?", answers: ["Boston Red Sox", "New York Mets", "Chicago Cubs", "Oakland Athletics"], correct: 1 },
  { category: "Sports", question: "What tennis player won Wimbledon five consecutive times (1980-1984)?", answers: ["John McEnroe", "Jimmy Connors", "Bjorn Borg", "Ivan Lendl"], correct: 2 },
  { category: "Sports", question: "Who was the NFL MVP in 1986?", answers: ["Joe Montana", "Lawrence Taylor", "Dan Marino", "Walter Payton"], correct: 1 },
  { category: "Sports", question: "What NASCAR driver won 7 Winston Cup championships?", answers: ["Richard Petty", "Dale Earnhardt", "Jeff Gordon", "Darrell Waltrip"], correct: 1 },
  { category: "Sports", question: "Who hit the famous 'Shot Heard Round the World' in 1985 NCAA tournament?", answers: ["Michael Jordan", "Christian Laettner", "Keith Smart", "Villanova's team"], correct: 2 },
  { category: "Sports", question: "What horse won the Triple Crown in 1978 (but famous throughout 80s)?", answers: ["Secretariat", "Affirmed", "Seattle Slew", "None in the 1980s"], correct: 3 },
  { category: "Sports", question: "Who was the Chicago Bears' legendary running back who retired in 1987?", answers: ["Jim Brown", "Walter Payton", "Gale Sayers", "Emmitt Smith"], correct: 1 },
  { category: "Sports", question: "What city's baseball team won the World Series in 1985?", answers: ["New York", "Kansas City", "St. Louis", "Los Angeles"], correct: 1 },
  { category: "Sports", question: "Who was the Edmonton Oilers' star player in the 1980s?", answers: ["Mark Messier", "Wayne Gretzky", "Jari Kurri", "Grant Fuhr"], correct: 1 },
  { category: "Sports", question: "What was Mike Tyson's record before his first loss?", answers: ["27-0", "31-0", "35-0", "37-0"], correct: 3 },
  { category: "Sports", question: "Who won the Heisman Trophy in 1988?", answers: ["Bo Jackson", "Barry Sanders", "Herschel Walker", "Tim Brown"], correct: 1 },
  { category: "Sports", question: "What NFL team was known as 'The Orange Crush' defense?", answers: ["Chicago Bears", "Denver Broncos", "New York Giants", "Pittsburgh Steelers"], correct: 1 },
  { category: "Sports", question: "Who beat Germany in the 1982 World Cup Final?", answers: ["Brazil", "Italy", "Argentina", "France"], correct: 1 },
  { category: "Sports", question: "What legendary coach led the San Francisco 49ers to 4 Super Bowls?", answers: ["Bill Walsh", "Don Shula", "Tom Landry", "Chuck Noll"], correct: 0 },
  { category: "Sports", question: "Who won the World Series in 1989?", answers: ["San Francisco Giants", "Oakland Athletics", "Los Angeles Dodgers", "Toronto Blue Jays"], correct: 1 },

  // POP CULTURE - Fads, Toys, Celebrities
  { category: "Pop Culture", question: "What toy line and cartoon featured 'Transformers, robots in disguise'?", answers: ["G.I. Joe", "Transformers", "Go-Bots", "M.A.S.K."], correct: 1 },
  { category: "Pop Culture", question: "What was the name of the Cabbage Patch Kids' birthplace?", answers: ["Babyland General Hospital", "Cabbage Patch Hospital", "Baby Land", "Patch General"], correct: 0 },
  { category: "Pop Culture", question: "What puzzle toy became a worldwide craze?", answers: ["Rubik's Cube", "Sudoku", "Crossword", "Jigsaw"], correct: 0 },
  { category: "Pop Culture", question: "What talking teddy bear was popular in the 1980s?", answers: ["Teddy Ruxpin", "Talking Ted", "Furby", "Care Bears"], correct: 0 },
  { category: "Pop Culture", question: "What electronic pet required you to feed and care for it?", answers: ["Furby", "Tamagotchi", "Giga Pet", "None, Tamagotchi was 90s"], correct: 3 },
  { category: "Pop Culture", question: "What were the colorful bears with symbols on their bellies called?", answers: ["Rainbow Bears", "Care Bears", "Gummi Bears", "Tenderheart Bears"], correct: 1 },
  { category: "Pop Culture", question: "What doll line featured 'She-Ra, Princess of Power'?", answers: ["Barbie", "My Little Pony", "Masters of the Universe", "Rainbow Brite"], correct: 2 },
  { category: "Pop Culture", question: "What children's TV host had a playhouse?", answers: ["Mr. Rogers", "Captain Kangaroo", "Pee-wee Herman", "Barney"], correct: 2 },
  { category: "Pop Culture", question: "What was the name of the exercise program featuring Jane Fonda?", answers: ["Jazzercise", "Aerobics", "Jane Fonda's Workout", "Step Aerobics"], correct: 2 },
  { category: "Pop Culture", question: "What colorful pony toys had brushable hair?", answers: ["Rainbow Ponies", "My Little Pony", "Pretty Pony", "Magic Ponies"], correct: 1 },
  { category: "Pop Culture", question: "What action figure line advertised 'A Real American Hero'?", answers: ["Action Man", "G.I. Joe", "Rambo", "Commando"], correct: 1 },
  { category: "Pop Culture", question: "What was the Rubik's Cube inventor's first name?", answers: ["Erno", "Rubik", "Ernst", "Rudolf"], correct: 0 },
  { category: "Pop Culture", question: "What candy was advertised with 'Taste the Rainbow'?", answers: ["M&Ms", "Skittles", "Starburst", "Nerds"], correct: 1 },
  { category: "Pop Culture", question: "What breakfast cereal featured a rabbit who wanted Trix?", answers: ["Lucky Charms", "Cocoa Puffs", "Trix", "Fruity Pebbles"], correct: 2 },
  { category: "Pop Culture", question: "What was the name of McDonald's purple character?", answers: ["Barney", "Grimace", "Purple Guy", "Big Mac"], correct: 1 },
  { category: "Pop Culture", question: "What toy robots could transform into vehicles?", answers: ["Go-Bots", "Transformers", "Robotech", "Voltron"], correct: 1 },
  { category: "Pop Culture", question: "What was the name of the Smurfs' enemy?", answers: ["Voldemort", "Gargamel", "Skeletor", "Shredder"], correct: 1 },
  { category: "Pop Culture", question: "What phrase did the Teenage Mutant Ninja Turtles say?", answers: ["Cowabunga", "Radical", "Tubular", "Awesome"], correct: 0 },
  { category: "Pop Culture", question: "What was the name of Strawberry Shortcake's cat?", answers: ["Custard", "Cream", "Vanilla", "Cupcake"], correct: 0 },
  { category: "Pop Culture", question: "What toy featured tiny colorful ponies with symbols?", answers: ["Rainbow Brite", "My Little Pony", "Pound Puppies", "Popples"], correct: 1 },
  { category: "Pop Culture", question: "What was the name of the villain in He-Man?", answers: ["Skeletor", "Hordak", "Beast Man", "Trap Jaw"], correct: 0 },
  { category: "Pop Culture", question: "What talking bear told bedtime stories?", answers: ["Teddy Ruxpin", "Care Bears", "Winnie the Pooh", "Paddington"], correct: 0 },
  { category: "Pop Culture", question: "What was the name of the crystal ball in She-Ra?", answers: ["Magic Mirror", "Crystal Ball", "Crystal Castle", "Magic Crystal"], correct: 2 },
  { category: "Pop Culture", question: "What were the small, colorful troll dolls with wild hair called?", answers: ["Trolls", "Norfin Trolls", "Treasure Trolls", "All of the above"], correct: 3 },
  { category: "Pop Culture", question: "What was the name of Scooby-Doo's nephew?", answers: ["Scrappy-Doo", "Scooby-Dum", "Yabba-Doo", "Dooby-Doo"], correct: 0 },

  // Additional MUSIC questions
  { category: "Music", question: "What band sang 'Girls on Film'?", answers: ["Culture Club", "Duran Duran", "Spandau Ballet", "The Human League"], correct: 1 },
  { category: "Music", question: "Who sang 'I Want to Know What Love Is'?", answers: ["Journey", "REO Speedwagon", "Foreigner", "Styx"], correct: 2 },
  { category: "Music", question: "What was Bon Jovi's first album called?", answers: ["7800 Degrees Fahrenheit", "Slippery When Wet", "Bon Jovi", "New Jersey"], correct: 2 },
  { category: "Music", question: "Who sang 'Total Eclipse of the Heart'?", answers: ["Pat Benatar", "Bonnie Tyler", "Heart", "Joan Jett"], correct: 1 },
  { category: "Music", question: "What band released 'Africa' in 1982?", answers: ["Journey", "Toto", "Asia", "Boston"], correct: 1 },
  { category: "Music", question: "Who was the lead singer of The Smiths?", answers: ["Robert Smith", "Morrissey", "Ian Curtis", "Bernard Sumner"], correct: 1 },
  { category: "Music", question: "What was Def Leppard's best-selling album?", answers: ["Pyromania", "Hysteria", "High 'n' Dry", "Adrenalize"], correct: 1 },
  { category: "Music", question: "Who sang 'Walking on Sunshine'?", answers: ["Bananarama", "The Bangles", "Katrina and the Waves", "The Go-Go's"], correct: 2 },
  { category: "Music", question: "What year did George Michael release 'Faith'?", answers: ["1985", "1986", "1987", "1988"], correct: 2 },
  { category: "Music", question: "Who was the lead singer of INXS?", answers: ["Bono", "Michael Hutchence", "Sting", "Billy Idol"], correct: 1 },

  // Additional MOVIES questions
  { category: "Movies", question: "What 1987 movie featured the line 'As you wish'?", answers: ["Labyrinth", "The Princess Bride", "Legend", "Willow"], correct: 1 },
  { category: "Movies", question: "Who directed Blade Runner?", answers: ["James Cameron", "Ridley Scott", "John Carpenter", "Paul Verhoeven"], correct: 1 },
  { category: "Movies", question: "What year was Scarface released?", answers: ["1981", "1983", "1985", "1987"], correct: 1 },
  { category: "Movies", question: "Who played Ripley in Aliens?", answers: ["Jamie Lee Curtis", "Sigourney Weaver", "Linda Hamilton", "Kathleen Turner"], correct: 1 },
  { category: "Movies", question: "What movie featured the DeLorean time machine?", answers: ["Back to the Future", "Weird Science", "Short Circuit", "Flight of the Navigator"], correct: 0 },
  { category: "Movies", question: "Who directed The Shining?", answers: ["Stanley Kubrick", "John Carpenter", "David Lynch", "Brian De Palma"], correct: 0 },
  { category: "Movies", question: "What 1984 movie featured a boy who could create things with his computer?", answers: ["WarGames", "Tron", "Weird Science", "D.A.R.Y.L."], correct: 2 },
  { category: "Movies", question: "Who played the villain in Die Hard?", answers: ["Jeremy Irons", "Alan Rickman", "Gary Oldman", "Christopher Walken"], correct: 1 },
  { category: "Movies", question: "What was the name of the hotel in The Shining?", answers: ["Overlook Hotel", "Stanley Hotel", "Timberline Lodge", "Grand Hotel"], correct: 0 },
  { category: "Movies", question: "What year was Platoon released?", answers: ["1984", "1985", "1986", "1987"], correct: 2 },

  // Additional TV SHOWS questions
  { category: "TV Shows", question: "What was Alf's favorite food?", answers: ["Pizza", "Cats", "Hot dogs", "Burgers"], correct: 1 },
  { category: "TV Shows", question: "Who played the title character in Magnum P.I.?", answers: ["Tom Selleck", "Bruce Willis", "Don Johnson", "Pierce Brosnan"], correct: 0 },
  { category: "TV Shows", question: "What was the name of the car in Knight Rider?", answers: ["KARR", "KITT", "KATT", "KATE"], correct: 1 },
  { category: "TV Shows", question: "Who was the host of Lifestyles of the Rich and Famous?", answers: ["Robin Leach", "Dick Clark", "Casey Kasem", "Ed McMahon"], correct: 0 },
  { category: "TV Shows", question: "What show featured Bo and Luke Duke?", answers: ["The Fall Guy", "The Dukes of Hazzard", "Knight Rider", "The A-Team"], correct: 1 },
  { category: "TV Shows", question: "Who played Sonny Crockett in Miami Vice?", answers: ["Philip Michael Thomas", "Don Johnson", "Edward James Olmos", "Bruce Willis"], correct: 1 },
  { category: "TV Shows", question: "What was the name of the spaceship in Battlestar Galactica?", answers: ["Enterprise", "Galactica", "Voyager", "Serenity"], correct: 1 },
  { category: "TV Shows", question: "Who was the boss in Who's the Boss?", answers: ["Tony Danza", "Judith Light", "Alyssa Milano", "Katherine Helmond"], correct: 1 },
  { category: "TV Shows", question: "What was Webster's last name?", answers: ["Long", "Papadapolis", "Drummond", "Tanner"], correct: 0 },
  { category: "TV Shows", question: "Who played Jessica Fletcher in Murder, She Wrote?", answers: ["Betty White", "Angela Lansbury", "Rue McClanahan", "Bea Arthur"], correct: 1 },

  // Additional VIDEO GAMES questions
  { category: "Video Games", question: "What was the princess's name in Super Mario Bros.?", answers: ["Princess Daisy", "Princess Zelda", "Princess Toadstool", "Princess Peach"], correct: 2 },
  { category: "Video Games", question: "What color is Mega Man?", answers: ["Red", "Blue", "Green", "Yellow"], correct: 1 },
  { category: "Video Games", question: "In what year was the original Legend of Zelda released?", answers: ["1985", "1986", "1987", "1988"], correct: 1 },
  { category: "Video Games", question: "What was Link's fairy companion called in later Zelda games?", answers: ["Tingle", "Navi", "Tatl", "Zelda had no fairy in 80s games"], correct: 3 },
  { category: "Video Games", question: "What was the first game in the Final Fantasy series released?", answers: ["1985", "1987", "1989", "1991"], correct: 1 },
  { category: "Video Games", question: "What company created the Game Boy?", answers: ["Sega", "Nintendo", "Atari", "Sony"], correct: 1 },
  { category: "Video Games", question: "What was the first handheld gaming system with interchangeable cartridges?", answers: ["Game Boy", "Game Gear", "Atari Lynx", "Microvision"], correct: 3 },
  { category: "Video Games", question: "Who is Mario's dinosaur companion? (introduced 1990, close to 80s)", answers: ["Bowser", "Koopa", "Yoshi", "Toad"], correct: 2 },
  { category: "Video Games", question: "What arcade game featured a frog crossing a road?", answers: ["Frogger", "Dig Dug", "Q*bert", "Centipede"], correct: 0 },
  { category: "Video Games", question: "What was the best-selling game for the NES?", answers: ["The Legend of Zelda", "Super Mario Bros.", "Duck Hunt", "Tetris"], correct: 1 },

  // Additional FASHION questions
  { category: "Fashion", question: "What brand's polo shirts were popular with the collar popped?", answers: ["Tommy Hilfiger", "Ralph Lauren", "Lacoste", "Izod"], correct: 3 },
  { category: "Fashion", question: "What were the bright, oversized shirts called?", answers: ["Muscle shirts", "Tank tops", "Hypercolor", "Oversized tees"], correct: 3 },
  { category: "Fashion", question: "What accessory was worn around the ankle?", answers: ["Ankle socks", "Ankle warmers", "Ankle bracelets", "All of the above"], correct: 3 },
  { category: "Fashion", question: "What pattern became popular thanks to Miami Vice?", answers: ["Stripes", "Paisley", "Pastel colors", "Polka dots"], correct: 2 },
  { category: "Fashion", question: "What type of shoes did Michael Jackson make famous?", answers: ["High tops", "Penny loafers", "Jellies", "White socks with black loafers"], correct: 3 },
  { category: "Fashion", question: "What was the name of the layered, teased hairstyle?", answers: ["The Perm", "The Wave", "The Mullet", "The Poof"], correct: 0 },
  { category: "Fashion", question: "What sunglasses brand became iconic in Top Gun?", answers: ["Oakley", "Ray-Ban", "Wayfarers", "Aviators"], correct: 3 },
  { category: "Fashion", question: "What type of jacket was popularized by Indiana Jones?", answers: ["Bomber jacket", "Leather jacket", "Denim jacket", "Windbreaker"], correct: 1 },
  { category: "Fashion", question: "What material was used for shiny, wind-resistant jackets?", answers: ["Leather", "Nylon", "Vinyl", "Polyester"], correct: 1 },
  { category: "Fashion", question: "What were the plastic shoes with holes called?", answers: ["Crocs", "Jellies", "Clogs", "Water shoes"], correct: 1 },

  // Additional TECHNOLOGY questions
  { category: "Technology", question: "What was the name of the first Apple portable computer?", answers: ["Macintosh Portable", "PowerBook", "iBook", "Apple IIc"], correct: 0 },
  { category: "Technology", question: "What year was the Commodore Amiga released?", answers: ["1983", "1985", "1987", "1989"], correct: 1 },
  { category: "Technology", question: "What was the resolution of the original Macintosh?", answers: ["320x200", "512x342", "640x480", "800x600"], correct: 1 },
  { category: "Technology", question: "What company created the Atari ST?", answers: ["Commodore", "Atari", "Apple", "IBM"], correct: 1 },
  { category: "Technology", question: "What was the storage capacity of a 5.25-inch floppy disk?", answers: ["180 KB or 360 KB", "720 KB", "1.44 MB", "2.88 MB"], correct: 0 },
  { category: "Technology", question: "What was the name of the first computer worm?", answers: ["Brain", "Morris Worm", "ILOVEYOU", "Melissa"], correct: 1 },
  { category: "Technology", question: "What year was MS-DOS released?", answers: ["1979", "1981", "1983", "1985"], correct: 1 },
  { category: "Technology", question: "What was the processor in the original IBM PC?", answers: ["Intel 8080", "Intel 8088", "Motorola 68000", "Zilog Z80"], correct: 1 },
  { category: "Technology", question: "What video game crash occurred in 1983?", answers: ["Console crash", "Atari shock", "North American video game crash", "Gaming depression"], correct: 2 },
  { category: "Technology", question: "What was the first 16-bit home computer?", answers: ["Commodore 64", "Atari ST", "Amiga", "TI-99/4A"], correct: 3 },

  // Additional SPORTS questions
  { category: "Sports", question: "Who was 'The Fridge' in football?", answers: ["William Perry", "Walter Payton", "Jim McMahon", "Mike Ditka"], correct: 0 },
  { category: "Sports", question: "What baseball player was known as 'Charlie Hustle'?", answers: ["Pete Rose", "Cal Ripken Jr.", "Wade Boggs", "Rickey Henderson"], correct: 0 },
  { category: "Sports", question: "Who won the 1986 Masters golf tournament?", answers: ["Jack Nicklaus", "Greg Norman", "Tom Watson", "Seve Ballesteros"], correct: 0 },
  { category: "Sports", question: "What team won Super Bowl XX in 1986?", answers: ["New York Giants", "Chicago Bears", "San Francisco 49ers", "Washington Redskins"], correct: 1 },
  { category: "Sports", question: "Who was the NBA's all-time leading scorer? (during the 80s)", answers: ["Wilt Chamberlain", "Kareem Abdul-Jabbar", "Michael Jordan", "Karl Malone"], correct: 1 },
  { category: "Sports", question: "What boxer was known as 'Iron Mike'?", answers: ["Mike Tyson", "Michael Spinks", "Evander Holyfield", "Riddick Bowe"], correct: 0 },
  { category: "Sports", question: "Who won the 1988 Summer Olympics 100m gold medal?", answers: ["Carl Lewis", "Ben Johnson", "Calvin Smith", "Linford Christie"], correct: 1 },
  { category: "Sports", question: "What baseball team did Nolan Ryan play for in 1989?", answers: ["California Angels", "Houston Astros", "Texas Rangers", "New York Mets"], correct: 2 },
  { category: "Sports", question: "Who was known as 'The Say Hey Kid'? (retired before 80s but still famous)", answers: ["Willie Mays", "Hank Aaron", "Mickey Mantle", "Joe DiMaggio"], correct: 0 },
  { category: "Sports", question: "What team won the Stanley Cup in 1984?", answers: ["New York Islanders", "Edmonton Oilers", "Montreal Canadiens", "Calgary Flames"], correct: 1 },

  // Additional POP CULTURE questions
  { category: "Pop Culture", question: "What was the name of the Ghostbusters' car?", answers: ["Ecto-1", "Ghost Mobile", "Spirit Wagon", "Phantom Ride"], correct: 0 },
  { category: "Pop Culture", question: "What were the names of the two old men in The Muppet Show?", answers: ["Bert and Ernie", "Statler and Waldorf", "Oscar and Felix", "Chip and Dale"], correct: 1 },
  { category: "Pop Culture", question: "What was the name of Inspector Gadget's niece?", answers: ["Penny", "Sophie", "Gadget Girl", "Inspector Jr."], correct: 0 },
  { category: "Pop Culture", question: "What was the name of the Teenage Mutant Ninja Turtles' rat sensei?", answers: ["Splinter", "Shredder", "Master Yoshi", "Sensei Rat"], correct: 0 },
  { category: "Pop Culture", question: "What were the Garbage Pail Kids a parody of?", answers: ["Transformers", "Cabbage Patch Kids", "Care Bears", "My Little Pony"], correct: 1 },
  { category: "Pop Culture", question: "What was the name of the Rubik's Cube with pictures instead of colors?", answers: ["Rubik's Picture Cube", "Rubik's Photo Cube", "Image Cube", "Snapshot Cube"], correct: 0 },
  { category: "Pop Culture", question: "What stuffed animal brand had a 'birth certificate'?", answers: ["Beanie Babies", "Cabbage Patch Kids", "Pound Puppies", "Care Bears"], correct: 1 },
  { category: "Pop Culture", question: "What video game character said 'It's-a me!'?", answers: ["Sonic", "Link", "Mario", "Pac-Man"], correct: 2 },
  { category: "Pop Culture", question: "What was the name of the marshmallow man in Ghostbusters?", answers: ["Marshmallow Man", "Stay Puft", "Mr. Mallow", "Puffy White"], correct: 1 },
  { category: "Pop Culture", question: "What was Max Headroom?", answers: ["A robot", "A computer-generated character", "An alien", "A cartoon"], correct: 1 },
  { category: "Pop Culture", question: "What board game involved removing a patient's organs?", answers: ["Operation", "Life", "Surgery", "Doctor Doctor"], correct: 0 },
  { category: "Pop Culture", question: "What cereal mascot was a cuckoo bird?", answers: ["Toucan Sam", "Sonny the Cuckoo Bird", "Cornelius", "Cocoa Puffs bird"], correct: 1 },
  { category: "Pop Culture", question: "What were the colorful, collectible pencil toppers called?", answers: ["Trolls", "Pencil Pals", "Toppers", "Erasers"], correct: 0 },
  { category: "Pop Culture", question: "What was the name of the Kool-Aid mascot?", answers: ["Mr. Kool", "Kool-Aid Man", "The Pitcher", "Red Guy"], correct: 1 },
  { category: "Pop Culture", question: "What puzzle featured interlocking plastic pieces?", answers: ["Jigsaw", "Rubik's Cube", "Rubik's Snake", "Tangram"], correct: 2 },
];
