var QUESTIONS = [
  // Animated Classics
  { category: "Animated Classics", question: "What year was Snow White and the Seven Dwarfs released?", answers: ["1935", "1937", "1940", "1942"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of Sleeping Beauty's prince?", answers: ["Prince Charming", "Prince Philip", "Prince Eric", "Prince Adam"], correct: 1 },
  { category: "Animated Classics", question: "In The Little Mermaid, what is Ariel's father's name?", answers: ["Poseidon", "Neptune", "Triton", "Titan"], correct: 2 },
  { category: "Animated Classics", question: "What does Hakuna Matata mean?", answers: ["Live long", "Be happy", "No worries", "Good luck"], correct: 2 },
  { category: "Animated Classics", question: "In Beauty and the Beast, what is the name of Gaston's sidekick?", answers: ["LeFou", "Lumiere", "Cogsworth", "Maurice"], correct: 0 },
  { category: "Animated Classics", question: "What is the name of Mulan's dragon companion?", answers: ["Mushu", "Sushi", "Wasabi", "Mooshi"], correct: 0 },
  { category: "Animated Classics", question: "How many dwarfs are in Snow White?", answers: ["5", "6", "7", "8"], correct: 2 },
  { category: "Animated Classics", question: "What is the name of the villainous lion in The Lion King?", answers: ["Scar", "Mufasa", "Simba", "Sarabi"], correct: 0 },
  { category: "Animated Classics", question: "In Aladdin, what is the name of Jasmine's pet tiger?", answers: ["Raja", "Rajah", "Iago", "Abu"], correct: 1 },
  { category: "Animated Classics", question: "What is Bambi's rabbit friend's name?", answers: ["Hopper", "Thumper", "Flower", "Faline"], correct: 1 },
  { category: "Animated Classics", question: "In Cinderella, what time does the spell break?", answers: ["11 PM", "Midnight", "1 AM", "Dawn"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of the toy store in Toy Story 2?", answers: ["Toy Palace", "Al's Toy Barn", "Andy's Toys", "Toy World"], correct: 1 },
  { category: "Animated Classics", question: "In Tangled, what is Rapunzel's chameleon named?", answers: ["Pascal", "Maximus", "Flynn", "Eugene"], correct: 0 },
  { category: "Animated Classics", question: "What animal does Emperor Kuzco turn into in The Emperor's New Groove?", answers: ["Monkey", "Llama", "Alpaca", "Donkey"], correct: 1 },
  { category: "Animated Classics", question: "In Pocahontas, what is the name of her hummingbird friend?", answers: ["Flit", "Meeko", "Percy", "Nakoma"], correct: 0 },
  { category: "Animated Classics", question: "What is the name of Ariel's best friend in The Little Mermaid?", answers: ["Sebastian", "Scuttle", "Flounder", "Triton"], correct: 2 },
  { category: "Animated Classics", question: "In 101 Dalmatians, what is Cruella's last name?", answers: ["De Vil", "De Evil", "Devil", "Deville"], correct: 0 },
  { category: "Animated Classics", question: "What type of animal is Flower in Bambi?", answers: ["Rabbit", "Deer", "Skunk", "Squirrel"], correct: 2 },
  { category: "Animated Classics", question: "In The Jungle Book, what kind of animal is Baloo?", answers: ["Panther", "Bear", "Tiger", "Monkey"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of the kingdom in Frozen?", answers: ["Arendelle", "Corona", "DunBroch", "Atlantica"], correct: 0 },
  { category: "Animated Classics", question: "In The Princess and the Frog, what city is the story set in?", answers: ["Miami", "Atlanta", "New Orleans", "Charleston"], correct: 2 },
  { category: "Animated Classics", question: "What does Cinderella's fairy godmother turn into a carriage?", answers: ["Watermelon", "Pumpkin", "Apple", "Squash"], correct: 1 },
  { category: "Animated Classics", question: "In Alice in Wonderland, what color is the Cheshire Cat?", answers: ["Blue and white", "Pink and purple", "Orange and black", "Purple and pink"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of Simba's mother?", answers: ["Nala", "Sarabi", "Sarafina", "Kiara"], correct: 1 },
  { category: "Animated Classics", question: "In Hercules, who trains the title character to be a hero?", answers: ["Zeus", "Hades", "Philoctetes", "Pegasus"], correct: 2 },
  { category: "Animated Classics", question: "What is the name of Belle's father in Beauty and the Beast?", answers: ["Maurice", "Gaston", "LeFou", "Lumiere"], correct: 0 },
  { category: "Animated Classics", question: "In Lilo & Stitch, what is Stitch's experiment number?", answers: ["626", "624", "628", "625"], correct: 0 },
  { category: "Animated Classics", question: "What kind of animal is Tod in The Fox and the Hound?", answers: ["Hound", "Fox", "Bear", "Rabbit"], correct: 1 },
  { category: "Animated Classics", question: "In Moana, what is the name of Moana's pet pig?", answers: ["Pua", "Hei Hei", "Tamatoa", "Maui"], correct: 0 },
  { category: "Animated Classics", question: "What is the name of the gargoyles' leader in The Hunchback of Notre Dame?", answers: ["Victor", "Hugo", "Laverne", "Quasimodo"], correct: 1 },

  // Pixar
  { category: "Pixar", question: "What is the name of Andy's neighbor in Toy Story?", answers: ["Sid", "Sam", "Steve", "Stan"], correct: 0 },
  { category: "Pixar", question: "In Finding Nemo, what type of fish is Dory?", answers: ["Clownfish", "Blue Tang", "Angelfish", "Butterflyfish"], correct: 1 },
  { category: "Pixar", question: "What is the name of the superhero family's surname in The Incredibles?", answers: ["Parker", "Parr", "Powers", "Prince"], correct: 1 },
  { category: "Pixar", question: "In Up, what is the name of the giant bird?", answers: ["Charlie", "Kevin", "Russell", "Doug"], correct: 1 },
  { category: "Pixar", question: "What is the name of the chef in Ratatouille?", answers: ["Linguini", "Remy", "Gusteau", "Skinner"], correct: 2 },
  { category: "Pixar", question: "In WALL-E, what does WALL-E stand for?", answers: ["Waste Allocation Load Lifter Earth-Class", "World Alliance Load Lifter Earth", "Waste and Litter Lifter Earth", "World Automated Load Lifter"], correct: 0 },
  { category: "Pixar", question: "What is the name of the pizza restaurant in Toy Story?", answers: ["Pizza Planet", "Planet Pizza", "Pizza World", "Cosmic Pizza"], correct: 0 },
  { category: "Pixar", question: "In Monsters, Inc., what is Sulley's full name?", answers: ["James P. Sullivan", "John P. Sullivan", "Jack P. Sullivan", "Jerry P. Sullivan"], correct: 0 },
  { category: "Pixar", question: "What is the name of Lightning McQueen's hometown in Cars?", answers: ["Radiator Springs", "Carburetor County", "Piston Peak", "Motor City"], correct: 0 },
  { category: "Pixar", question: "In Inside Out, what is the name of Riley's imaginary friend?", answers: ["Bing Bang", "Bing Bong", "King Kong", "Ping Pong"], correct: 1 },
  { category: "Pixar", question: "What is the name of the antagonist in Toy Story 3?", answers: ["Lots-o'-Huggin' Bear", "Big Baby", "Ken", "Barbie"], correct: 0 },
  { category: "Pixar", question: "In Finding Dory, what disorder does Dory suffer from?", answers: ["Amnesia", "Short-term memory loss", "Long-term memory loss", "Dementia"], correct: 1 },
  { category: "Pixar", question: "What is the name of the daycare in Toy Story 3?", answers: ["Sunny Side", "Sunnyside", "Happy Days", "Playtime"], correct: 1 },
  { category: "Pixar", question: "In Brave, what is Merida's mother's name?", answers: ["Eleanor", "Elinor", "Elizabeth", "Evangeline"], correct: 1 },
  { category: "Pixar", question: "What is the name of the villain in The Incredibles?", answers: ["Syndrome", "Screenslaver", "Bomb Voyage", "Underminer"], correct: 0 },
  { category: "Pixar", question: "In Coco, what is Miguel's great-great-grandfather's name?", answers: ["Ernesto de la Cruz", "Hector", "Julio", "Felipe"], correct: 1 },
  { category: "Pixar", question: "What does Remy want to be in Ratatouille?", answers: ["A waiter", "A chef", "A food critic", "A restaurant owner"], correct: 1 },
  { category: "Pixar", question: "In A Bug's Life, what is the name of the ant colony's princess?", answers: ["Atta", "Dot", "The Queen", "Gypsy"], correct: 0 },
  { category: "Pixar", question: "What type of car is Lightning McQueen?", answers: ["Stock car", "Race car", "Sports car", "Formula One"], correct: 1 },
  { category: "Pixar", question: "In Toy Story, what is Woody's horse named?", answers: ["Buttercup", "Bullseye", "Thunder", "Spirit"], correct: 1 },
  { category: "Pixar", question: "What is the name of the elderly man in Up?", answers: ["Carl Fredricksen", "Charles Muntz", "Russell", "Kevin"], correct: 0 },
  { category: "Pixar", question: "In Monsters University, what fraternity do Mike and Sulley join?", answers: ["Oozma Kappa", "Roar Omega Roar", "Jaws Theta Chi", "Slugma Slugma Kappa"], correct: 0 },
  { category: "Pixar", question: "What is the name of the dentist in Finding Nemo?", answers: ["Dr. Sherman", "Dr. Smith", "Dr. Sanders", "Dr. Stevens"], correct: 0 },
  { category: "Pixar", question: "In The Incredibles, what is Dash's real name?", answers: ["Dashiell", "Daniel", "David", "Damon"], correct: 0 },
  { category: "Pixar", question: "What is the name of the witch in Brave?", answers: ["She has no name", "The Witch", "Mor'du", "Elinor"], correct: 0 },
  { category: "Pixar", question: "In Soul, what is Joe Gardner's profession?", answers: ["Jazz musician", "Music teacher", "Both A and B", "Concert pianist"], correct: 2 },
  { category: "Pixar", question: "What is the name of the spaceship in WALL-E?", answers: ["Axiom", "Exodus", "Genesis", "Haven"], correct: 0 },
  { category: "Pixar", question: "In Turning Red, what animal does Mei turn into?", answers: ["Red Fox", "Red Panda", "Red Wolf", "Red Bear"], correct: 1 },
  { category: "Pixar", question: "What is the name of Nemo's mother?", answers: ["Coral", "Pearl", "Marina", "Dory"], correct: 0 },
  { category: "Pixar", question: "In Luca, where is the story set?", answers: ["Sicily", "Sardinia", "Italian Riviera", "Amalfi Coast"], correct: 2 },

  // Live Action
  { category: "Live Action", question: "What is the name of the flying car in Chitty Chitty Bang Bang?", answers: ["Chitty Chitty Bang Bang", "The Flying Car", "GEN 11", "Caractacus"], correct: 0 },
  { category: "Live Action", question: "In Pirates of the Caribbean, what is Captain Jack Sparrow's ship called?", answers: ["The Flying Dutchman", "The Black Pearl", "The Queen Anne's Revenge", "The Interceptor"], correct: 1 },
  { category: "Live Action", question: "What is the name of the magical nanny played by Julie Andrews?", answers: ["Mary Poppins", "Mrs. Doubtfire", "Nanny McPhee", "The Sound of Music"], correct: 0 },
  { category: "Live Action", question: "In The Parent Trap (1998), where do the twins first meet?", answers: ["School", "Summer camp", "A wedding", "Disney World"], correct: 1 },
  { category: "Live Action", question: "What sport does the movie The Mighty Ducks focus on?", answers: ["Baseball", "Basketball", "Hockey", "Soccer"], correct: 2 },
  { category: "Live Action", question: "In Freaky Friday, what causes the mother and daughter to switch bodies?", answers: ["A spell", "Fortune cookies", "A magic mirror", "A wish"], correct: 1 },
  { category: "Live Action", question: "What is the name of the high school in High School Musical?", answers: ["East High", "West High", "Central High", "North High"], correct: 0 },
  { category: "Live Action", question: "In The Princess Diaries, which country is Mia the princess of?", answers: ["Genovia", "Aldovia", "Belgravia", "Cordinia"], correct: 0 },
  { category: "Live Action", question: "What is the name of the von Trapp family's nanny in The Sound of Music?", answers: ["Mary", "Maria", "Martha", "Margaret"], correct: 1 },
  { category: "Live Action", question: "In Tron, what is the name of the digital world?", answers: ["The Grid", "The Matrix", "Cyberspace", "The System"], correct: 0 },
  { category: "Live Action", question: "What is the name of Johnny Depp's character in Alice in Wonderland?", answers: ["The White Rabbit", "The Cheshire Cat", "The Mad Hatter", "The March Hare"], correct: 2 },
  { category: "Live Action", question: "In Maleficent, who plays the title character?", answers: ["Angelina Jolie", "Cate Blanchett", "Charlize Theron", "Helena Bonham Carter"], correct: 0 },
  { category: "Live Action", question: "What is the name of the school in Sky High?", answers: ["Hero High", "Sky High", "Super School", "Power Academy"], correct: 1 },
  { category: "Live Action", question: "In Enchanted, where does Giselle come from?", answers: ["Wonderland", "Andalasia", "Far Far Away", "Genovia"], correct: 1 },
  { category: "Live Action", question: "What are the names of the twins in The Parent Trap?", answers: ["Annie and Hallie", "Amy and Holly", "Anna and Helen", "Alice and Hannah"], correct: 0 },
  { category: "Live Action", question: "In Cool Runnings, which country's bobsled team is featured?", answers: ["Trinidad", "Jamaica", "Barbados", "Haiti"], correct: 1 },
  { category: "Live Action", question: "What is the name of the main character in Tron: Legacy?", answers: ["Kevin Flynn", "Sam Flynn", "Alan Bradley", "Clu"], correct: 1 },
  { category: "Live Action", question: "In Cruella, what fashion house does the Baroness run?", answers: ["House of Baroness", "Baroness Couture", "Liberty", "Her own name"], correct: 3 },
  { category: "Live Action", question: "What is the name of the camp in Camp Rock?", answers: ["Rock Camp", "Camp Rock", "Camp Star", "Music Camp"], correct: 1 },
  { category: "Live Action", question: "In The Jungle Book (2016), who voices Baloo?", answers: ["Bill Murray", "Tom Hanks", "Robin Williams", "Jim Carrey"], correct: 0 },

  // Theme Parks
  { category: "Theme Parks", question: "What year did Disneyland open?", answers: ["1953", "1955", "1957", "1960"], correct: 1 },
  { category: "Theme Parks", question: "What is the tallest structure at Walt Disney World?", answers: ["Cinderella Castle", "Expedition Everest", "Tower of Terror", "Space Mountain"], correct: 1 },
  { category: "Theme Parks", question: "Which Disney park has a Tree of Life?", answers: ["Magic Kingdom", "Animal Kingdom", "Epcot", "Hollywood Studios"], correct: 1 },
  { category: "Theme Parks", question: "What does Epcot stand for?", answers: ["Experimental Prototype Community of Tomorrow", "Entertainment Park Community of Tomorrow", "Experimental Park Community of Tomorrow", "Experimental Prototype City of Tomorrow"], correct: 0 },
  { category: "Theme Parks", question: "In which park would you find the Haunted Mansion?", answers: ["Epcot", "Animal Kingdom", "Magic Kingdom", "Hollywood Studios"], correct: 2 },
  { category: "Theme Parks", question: "What is the name of the castle at Disneyland?", answers: ["Cinderella Castle", "Sleeping Beauty Castle", "Belle's Castle", "Snow White's Castle"], correct: 1 },
  { category: "Theme Parks", question: "Which land was added to Disneyland in 1993?", answers: ["Toontown", "Fantasyland", "Tomorrowland", "Frontierland"], correct: 0 },
  { category: "Theme Parks", question: "What is the name of the shopping and entertainment district at Walt Disney World?", answers: ["Downtown Disney", "Disney Springs", "Disney Village", "Disney Marketplace"], correct: 1 },
  { category: "Theme Parks", question: "Which Disney park opened first outside the United States?", answers: ["Disneyland Paris", "Tokyo Disneyland", "Hong Kong Disneyland", "Shanghai Disneyland"], correct: 1 },
  { category: "Theme Parks", question: "What mountain attraction features the Abominable Snowman?", answers: ["Space Mountain", "Thunder Mountain", "Splash Mountain", "Expedition Everest"], correct: 3 },
  { category: "Theme Parks", question: "In which park can you ride Guardians of the Galaxy: Cosmic Rewind?", answers: ["Magic Kingdom", "Epcot", "Hollywood Studios", "Animal Kingdom"], correct: 1 },
  { category: "Theme Parks", question: "What is the name of the nighttime show at Magic Kingdom?", answers: ["Fantasmic", "Happily Ever After", "Illuminations", "World of Color"], correct: 1 },
  { category: "Theme Parks", question: "Which attraction uses the slogan 'The Happiest Cruise That Ever Sailed'?", answers: ["Pirates of the Caribbean", "It's a Small World", "Jungle Cruise", "Splash Mountain"], correct: 1 },
  { category: "Theme Parks", question: "What year did Walt Disney World open?", answers: ["1969", "1971", "1973", "1975"], correct: 1 },
  { category: "Theme Parks", question: "Which Disney park has a giant golf ball as its icon?", answers: ["Magic Kingdom", "Epcot", "Hollywood Studios", "Animal Kingdom"], correct: 1 },
  { category: "Theme Parks", question: "What is the name of the Star Wars land at Disney parks?", answers: ["Star Wars Galaxy", "Galaxy's Edge", "Star Wars World", "Black Spire Outpost"], correct: 1 },
  { category: "Theme Parks", question: "How many countries are represented in Epcot's World Showcase?", answers: ["9", "11", "13", "15"], correct: 1 },
  { category: "Theme Parks", question: "What is the name of Disneyland Paris's castle?", answers: ["Sleeping Beauty Castle", "Cinderella Castle", "Belle's Castle", "Aurora's Castle"], correct: 0 },
  { category: "Theme Parks", question: "Which mountain is the oldest in the Magic Kingdom?", answers: ["Space Mountain", "Big Thunder Mountain", "Splash Mountain", "Expedition Everest"], correct: 0 },
  { category: "Theme Parks", question: "What is the name of the resort hotel shaped like a giant swan?", answers: ["Swan Hotel", "Disney Swan", "Walt Disney Swan", "Swan Resort"], correct: 2 },
  { category: "Theme Parks", question: "In which land would you find the Matterhorn Bobsleds?", answers: ["Tomorrowland", "Fantasyland", "Frontierland", "Adventureland"], correct: 1 },
  { category: "Theme Parks", question: "What was the first Disney park to open in Asia?", answers: ["Hong Kong Disneyland", "Shanghai Disneyland", "Tokyo Disneyland", "Tokyo DisneySea"], correct: 2 },
  { category: "Theme Parks", question: "Which attraction was the first to use Audio-Animatronics?", answers: ["Haunted Mansion", "Tiki Room", "Pirates of the Caribbean", "Jungle Cruise"], correct: 1 },
  { category: "Theme Parks", question: "What is the name of the volcano at Tokyo DisneySea?", answers: ["Mount Fuji", "Mount Prometheus", "Mount Vesuvius", "Mount Olympus"], correct: 1 },
  { category: "Theme Parks", question: "Which park features the ride Avatar Flight of Passage?", answers: ["Magic Kingdom", "Animal Kingdom", "Epcot", "Hollywood Studios"], correct: 1 },

  // Disney+/Marvel/Star Wars
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the Mandalorian's ship?", answers: ["Razor Crest", "Slave I", "Millennium Falcon", "X-Wing"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "In WandaVision, what is the name of the town where Wanda and Vision live?", answers: ["Westview", "Eastview", "Pleasantville", "Stepford"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "What is Baby Yoda's real name?", answers: ["Yoda Jr.", "Grogu", "Grogo", "Yiddle"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In The Falcon and the Winter Soldier, who becomes the new Captain America?", answers: ["Bucky Barnes", "Sam Wilson", "John Walker", "Isaiah Bradley"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What planet is Ahsoka Tano searching for in her series?", answers: ["Tatooine", "Mandalore", "Thrawn", "Peridea"], correct: 3 },
  { category: "Disney+/Marvel/Star Wars", question: "In Loki, what is the name of the organization that monitors the timeline?", answers: ["S.H.I.E.L.D.", "TVA", "Avengers", "S.W.O.R.D."], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of Ms. Marvel's superhero alias?", answers: ["Kamala Khan", "Ms. Marvel", "Captain Marvel", "The Marvelous"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Andor, what is Cassian's home planet?", answers: ["Coruscant", "Kenari", "Ferrix", "Aldhani"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "Who is the main antagonist in She-Hulk?", answers: ["Abomination", "Titania", "Intelligencia", "Hulk"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Obi-Wan Kenobi, who plays young Leia?", answers: ["Vivien Lyra Blair", "Millie Bobby Brown", "Mckenna Grace", "Elsie Fisher"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "What species is Ahsoka Tano?", answers: ["Twi'lek", "Togruta", "Zabrak", "Human"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Moon Knight, what is Marc Spector's other personality named?", answers: ["Jake Lockley", "Steven Grant", "Both A and B", "Mr. Knight"], correct: 2 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the droid in Andor?", answers: ["K-2SO", "B2EMO", "C-3PO", "R2-D2"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Secret Invasion, who leads the Skrull invasion?", answers: ["Talos", "Gravik", "Nick Fury", "G'iah"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the main character in The Book of Boba Fett besides Boba?", answers: ["Mando", "Fennec Shand", "Cad Bane", "Grogu"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Hawkeye, what is Kate Bishop's dog named?", answers: ["Lucky", "Arrow", "Clint", "Pizza Dog"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "What organization does Monica Rambeau work for in WandaVision?", answers: ["S.H.I.E.L.D.", "S.W.O.R.D.", "A.I.M.", "Hydra"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In The Mandalorian, what is the name of the Darksaber?", answers: ["It's just called the Darksaber", "Mandalore's Blade", "The Black Saber", "Death's Edge"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the main antagonist in Loki Season 1?", answers: ["Kang", "He Who Remains", "Mobius", "Ravonna"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Star Wars: The Bad Batch, what is the team's ship called?", answers: ["The Marauder", "The Havoc Marauder", "The Bad Batch", "The Clone Ship"], correct: 1 },

  // Music
  { category: "Music", question: "What song does Elsa sing in Frozen while building her ice palace?", answers: ["Into the Unknown", "Let It Go", "Show Yourself", "For the First Time"], correct: 1 },
  { category: "Music", question: "In The Lion King, who sings 'Circle of Life'?", answers: ["Elton John", "Carmen Twillie", "Tim Rice", "Hans Zimmer"], correct: 1 },
  { category: "Music", question: "What is the name of the song Moana sings while crossing the reef?", answers: ["We Know the Way", "How Far I'll Go", "Where You Are", "Shiny"], correct: 1 },
  { category: "Music", question: "Who composed the music for The Little Mermaid?", answers: ["Alan Menken", "Howard Ashman", "Tim Rice", "Elton John"], correct: 0 },
  { category: "Music", question: "What song do the mice sing while making Cinderella's dress?", answers: ["Bibbidi-Bobbidi-Boo", "A Dream Is a Wish", "Sing Sweet Nightingale", "The Work Song"], correct: 3 },
  { category: "Music", question: "In Beauty and the Beast, what song do Lumiere and the servants sing?", answers: ["Be Our Guest", "Something There", "Beauty and the Beast", "Belle"], correct: 0 },
  { category: "Music", question: "Who sings 'You've Got a Friend in Me' from Toy Story?", answers: ["Randy Newman", "Billy Joel", "Elton John", "Paul Simon"], correct: 0 },
  { category: "Music", question: "What is the opening song in The Lion King?", answers: ["Hakuna Matata", "I Just Can't Wait to Be King", "Circle of Life", "Be Prepared"], correct: 2 },
  { category: "Music", question: "In Aladdin, what is the first song sung?", answers: ["Arabian Nights", "One Jump Ahead", "Friend Like Me", "A Whole New World"], correct: 0 },
  { category: "Music", question: "Who wrote the songs for Frozen?", answers: ["Kristen Anderson-Lopez and Robert Lopez", "Alan Menken", "Lin-Manuel Miranda", "Elton John and Tim Rice"], correct: 0 },
  { category: "Music", question: "What song does Maui sing in Moana?", answers: ["You're Welcome", "We Know the Way", "Shiny", "Where You Are"], correct: 0 },
  { category: "Music", question: "In Mulan, what song does Mulan sing while contemplating her identity?", answers: ["Honor to Us All", "Reflection", "I'll Make a Man Out of You", "A Girl Worth Fighting For"], correct: 1 },
  { category: "Music", question: "Who sings the villainous song 'Be Prepared' in The Lion King?", answers: ["Mufasa", "Scar", "Zazu", "The Hyenas"], correct: 1 },
  { category: "Music", question: "What is the title song of Pocahontas?", answers: ["Just Around the Riverbend", "Colors of the Wind", "Savages", "Steady as the Beating Drum"], correct: 1 },
  { category: "Music", question: "In Tangled, what song do Rapunzel and Flynn sing in the boat?", answers: ["When Will My Life Begin", "I See the Light", "Mother Knows Best", "I've Got a Dream"], correct: 1 },
  { category: "Music", question: "Who composed the music for Coco?", answers: ["Lin-Manuel Miranda", "Michael Giacchino", "Randy Newman", "Thomas Newman"], correct: 1 },
  { category: "Music", question: "What song does Gaston sing about himself in Beauty and the Beast?", answers: ["Be Our Guest", "Gaston", "The Mob Song", "Belle"], correct: 1 },
  { category: "Music", question: "In Encanto, who doesn't get a song about their gift?", answers: ["Luisa", "Isabela", "Dolores", "Antonio"], correct: 2 },
  { category: "Music", question: "What is the name of the tavern song in Tangled?", answers: ["When Will My Life Begin", "I've Got a Dream", "Mother Knows Best", "I See the Light"], correct: 1 },
  { category: "Music", question: "Who wrote the music for Moana?", answers: ["Lin-Manuel Miranda", "Alan Menken", "Kristen Anderson-Lopez", "Elton John"], correct: 0 },
  { category: "Music", question: "In The Princess and the Frog, what song does Dr. Facilier sing?", answers: ["Friends on the Other Side", "Down in New Orleans", "Dig a Little Deeper", "Almost There"], correct: 0 },
  { category: "Music", question: "What is the opening number of Frozen 2?", answers: ["Into the Unknown", "Some Things Never Change", "All Is Found", "The Next Right Thing"], correct: 1 },
  { category: "Music", question: "In Hercules, who sings the narrative songs?", answers: ["Zeus", "The Muses", "Philoctetes", "Hades"], correct: 1 },
  { category: "Music", question: "What song does Sebastian sing to convince Ariel to stay underwater?", answers: ["Part of Your World", "Under the Sea", "Kiss the Girl", "Poor Unfortunate Souls"], correct: 1 },
  { category: "Music", question: "Who wrote 'You'll Be in My Heart' from Tarzan?", answers: ["Elton John", "Phil Collins", "Sting", "Randy Newman"], correct: 1 },

  // Characters
  { category: "Characters", question: "What is Mickey Mouse's original name?", answers: ["Mortimer Mouse", "Michael Mouse", "Morris Mouse", "Martin Mouse"], correct: 0 },
  { category: "Characters", question: "What are the names of Donald Duck's three nephews?", answers: ["Huey, Dewey, and Louie", "Harry, Danny, and Larry", "Henry, Dennis, and Louis", "Hugh, Drew, and Lou"], correct: 0 },
  { category: "Characters", question: "What is Goofy's son's name?", answers: ["Max", "Maximilian", "Maximus", "Maxwell"], correct: 0 },
  { category: "Characters", question: "Who is Mickey Mouse's girlfriend?", answers: ["Daisy Duck", "Minnie Mouse", "Clarabelle Cow", "Felicity Fieldmouse"], correct: 1 },
  { category: "Characters", question: "What is Donald Duck's middle name?", answers: ["Fauntleroy", "Ferdinand", "Francis", "Frederick"], correct: 0 },
  { category: "Characters", question: "Who are the Fairy Godmothers in Sleeping Beauty?", answers: ["Faith, Hope, and Charity", "Flora, Fauna, and Merryweather", "Fiona, Felicity, and Mary", "Florence, Faye, and Margaret"], correct: 1 },
  { category: "Characters", question: "What is the name of Ariel's seagull friend?", answers: ["Scuttle", "Sebastian", "Flounder", "Triton"], correct: 0 },
  { category: "Characters", question: "Who is the fashion designer mouse in The Rescuers?", answers: ["Bernard", "Bianca", "Orville", "None - no fashion designer"], correct: 3 },
  { category: "Characters", question: "What are the names of Cinderella's stepsisters?", answers: ["Drizella and Anastasia", "Griselda and Annabella", "Drusilla and Alexandria", "Gabriella and Arabella"], correct: 0 },
  { category: "Characters", question: "What is the name of Belle's horse in Beauty and the Beast?", answers: ["Maximus", "Achilles", "Philippe", "Angus"], correct: 2 },
  { category: "Characters", question: "Who is Bambi's skunk friend?", answers: ["Flower", "Thumper", "Faline", "Friend Owl"], correct: 0 },
  { category: "Characters", question: "What is the name of Kristoff's reindeer in Frozen?", answers: ["Sven", "Hans", "Olaf", "Ryder"], correct: 0 },
  { category: "Characters", question: "Who is the leader of the seven dwarfs?", answers: ["Grumpy", "Doc", "Happy", "Sleepy"], correct: 1 },
  { category: "Characters", question: "What is the name of Jasmine's father in Aladdin?", answers: ["The Sultan", "King Mustafa", "Emperor Ali", "Shah Jafar"], correct: 0 },
  { category: "Characters", question: "Who is Merida's mother in Brave?", answers: ["Eleanor", "Elinor", "Elizabeth", "Elaine"], correct: 1 },
  { category: "Characters", question: "What is the name of Tarzan's gorilla mother?", answers: ["Kala", "Terk", "Kerchak", "Tantor"], correct: 0 },
  { category: "Characters", question: "Who is the cricket in Mulan?", answers: ["Cri-Kee", "Mushu", "Khan", "Ling"], correct: 0 },
  { category: "Characters", question: "What is the name of Alice's cat in Alice in Wonderland?", answers: ["Cheshire", "Dinah", "Duchess", "Tabitha"], correct: 1 },
  { category: "Characters", question: "Who is the toy dinosaur in Toy Story?", answers: ["Rex", "Trixie", "Dino", "Barney"], correct: 0 },
  { category: "Characters", question: "What is the name of Esmeralda's goat in The Hunchback of Notre Dame?", answers: ["Djali", "Clopin", "Phoebus", "Laverne"], correct: 0 },
  { category: "Characters", question: "Who is Rapunzel's chameleon companion?", answers: ["Pascal", "Maximus", "Flynn", "Eugene"], correct: 0 },
  { category: "Characters", question: "What is the name of the dog in Peter Pan?", answers: ["Nana", "Lady", "Perdita", "Tramp"], correct: 0 },
  { category: "Characters", question: "Who is the ringmaster in Dumbo?", answers: ["The Ringmaster", "Mr. Stork", "Timothy", "Casey Jr."], correct: 0 },
  { category: "Characters", question: "What is the name of Anna's horse in Frozen?", answers: ["Sven", "Hans", "Sitron", "Kjekk"], correct: 2 },
  { category: "Characters", question: "Who is the albatross in The Rescuers?", answers: ["Orville", "Wilbur", "Bernard", "Evinrude"], correct: 0 },

  // Villains
  { category: "Villains", question: "Who is the villain in Sleeping Beauty?", answers: ["Maleficent", "Ursula", "Evil Queen", "Cruella"], correct: 0 },
  { category: "Villains", question: "What is the name of the villain in 101 Dalmatians?", answers: ["Cruella de Vil", "Maleficent", "Lady Tremaine", "Queen of Hearts"], correct: 0 },
  { category: "Villains", question: "Who is the sea witch in The Little Mermaid?", answers: ["Morgana", "Ursula", "Vanessa", "Marina"], correct: 1 },
  { category: "Villains", question: "What is Jafar's parrot's name in Aladdin?", answers: ["Iago", "Abu", "Rajah", "Cassim"], correct: 0 },
  { category: "Villains", question: "Who is the villain in Tarzan?", answers: ["Kerchak", "Clayton", "Sabor", "Tantor"], correct: 1 },
  { category: "Villains", question: "What is the name of the villain in Tangled?", answers: ["Mother Gothel", "Lady Tremaine", "Maleficent", "Evil Queen"], correct: 0 },
  { category: "Villains", question: "Who is the main antagonist in The Princess and the Frog?", answers: ["Dr. Facilier", "Lawrence", "Mama Odie", "Prince Naveen"], correct: 0 },
  { category: "Villains", question: "What is Scar's real name in The Lion King?", answers: ["Taka", "Mufasa Jr.", "Simba Sr.", "He was always named Scar"], correct: 0 },
  { category: "Villains", question: "Who is the villain in Hercules?", answers: ["Zeus", "Hades", "Pain", "Panic"], correct: 1 },
  { category: "Villains", question: "What is the name of the villain in The Hunchback of Notre Dame?", answers: ["Frollo", "Phoebus", "Clopin", "Quasimodo"], correct: 0 },
  { category: "Villains", question: "Who is the antagonist in Pocahontas?", answers: ["John Smith", "Governor Ratcliffe", "Kocoum", "Thomas"], correct: 1 },
  { category: "Villains", question: "What is the name of the villain in Wreck-It Ralph?", answers: ["King Candy/Turbo", "Ralph", "Vanellope", "Fix-It Felix"], correct: 0 },
  { category: "Villains", question: "Who is the villain in Big Hero 6?", answers: ["Yokai/Robert Callaghan", "Alistair Krei", "Tadashi", "Hiro"], correct: 0 },
  { category: "Villains", question: "What is the Queen's name in Snow White?", answers: ["Grimhilde", "Maleficent", "Ravenna", "Regina"], correct: 0 },
  { category: "Villains", question: "Who is the main antagonist in Moana?", answers: ["Tamatoa", "Te Ka", "Maui", "Te Fiti"], correct: 1 },
  { category: "Villains", question: "What is the name of Gaston's sidekick?", answers: ["LeFou", "Maurice", "Lumiere", "Cogsworth"], correct: 0 },
  { category: "Villains", question: "Who is the villain in The Emperor's New Groove?", answers: ["Kuzco", "Pacha", "Yzma", "Kronk"], correct: 2 },
  { category: "Villains", question: "What is the name of the villain in Atlantis: The Lost Empire?", answers: ["Commander Rourke", "Milo", "Helga", "Kida"], correct: 0 },
  { category: "Villains", question: "Who is the main antagonist in Frozen?", answers: ["Elsa", "Hans", "The Duke of Weselton", "Marshmallow"], correct: 1 },
  { category: "Villains", question: "What is the name of the villain in Treasure Planet?", answers: ["Long John Silver", "Captain Amelia", "Scroop", "Mr. Arrow"], correct: 0 },
  { category: "Villains", question: "Who is the villain in The Incredibles 2?", answers: ["Syndrome", "Screenslaver/Evelyn Deavor", "Bomb Voyage", "Underminer"], correct: 1 },
  { category: "Villains", question: "What is the name of the villain in Raya and the Last Dragon?", answers: ["Namaari", "Sisu", "Boun", "Tong"], correct: 0 },
  { category: "Villains", question: "Who is the antagonist in Zootopia?", answers: ["Mayor Lionheart", "Assistant Mayor Bellwether", "Nick Wilde", "Mr. Big"], correct: 1 },
  { category: "Villains", question: "What is Captain Hook's fear in Peter Pan?", answers: ["Crocodiles", "Water", "Heights", "Pan"], correct: 0 },
  { category: "Villains", question: "Who is the villain in Mulan?", answers: ["Shan Yu", "Chi-Fu", "General Li", "The Emperor"], correct: 0 },

  // More Animated Classics
  { category: "Animated Classics", question: "What kind of flower does the Beast give Belle?", answers: ["Rose", "Lily", "Tulip", "Daisy"], correct: 0 },
  { category: "Animated Classics", question: "How many sisters does Ariel have?", answers: ["5", "6", "7", "8"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of Wendy's dog in Peter Pan?", answers: ["Nana", "Lady", "Perdita", "Pongo"], correct: 0 },
  { category: "Animated Classics", question: "In Frozen, what is the name of the kingdom Hans is from?", answers: ["Southern Isles", "Northern Isles", "Western Isles", "Eastern Isles"], correct: 0 },
  { category: "Animated Classics", question: "What does the Evil Queen ask the mirror in Snow White?", answers: ["Who's the prettiest?", "Who's the fairest?", "Who's the most beautiful?", "Who's the loveliest?"], correct: 1 },
  { category: "Animated Classics", question: "In Lady and the Tramp, what kind of dog is Lady?", answers: ["Beagle", "Cocker Spaniel", "Poodle", "Terrier"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of the toy store owner in Toy Story 2?", answers: ["Al McWhiggin", "Andy", "Sid", "Woody"], correct: 0 },
  { category: "Animated Classics", question: "In Dumbo, what is Timothy?", answers: ["Elephant", "Mouse", "Bird", "Rabbit"], correct: 1 },
  { category: "Animated Classics", question: "What color is Dumbo's feather?", answers: ["White", "Blue", "Black", "Red"], correct: 2 },
  { category: "Animated Classics", question: "In Robin Hood, what animal is Robin?", answers: ["Bear", "Fox", "Wolf", "Rabbit"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of Geppetto's cat in Pinocchio?", answers: ["Figaro", "Cleo", "Jiminy", "Stromboli"], correct: 0 },
  { category: "Animated Classics", question: "In The Aristocats, what is the mother cat's name?", answers: ["Marie", "Duchess", "Berlioz", "Toulouse"], correct: 1 },
  { category: "Animated Classics", question: "What vegetable is Rapunzel's tower surrounded by in the original fairy tale (referenced in Tangled)?", answers: ["Lettuce", "Rapunzel (vegetable)", "Cabbage", "Carrots"], correct: 1 },
  { category: "Animated Classics", question: "In Oliver & Company, what city is the movie set in?", answers: ["Los Angeles", "New York", "Chicago", "Boston"], correct: 1 },
  { category: "Animated Classics", question: "What is the name of the genie in Aladdin?", answers: ["Genie", "He has no name", "Robin", "Jafar"], correct: 1 },
  { category: "Animated Classics", question: "In Encanto, what is the family's last name?", answers: ["Madrigal", "Martinez", "Marquez", "Miranda"], correct: 0 },
  { category: "Animated Classics", question: "What is Mirabel's gift in Encanto?", answers: ["Strength", "Healing", "She doesn't have one", "Shapeshifting"], correct: 2 },
  { category: "Animated Classics", question: "In Big Hero 6, what is Baymax?", answers: ["A robot", "A healthcare companion", "An android", "A superhero"], correct: 1 },
  { category: "Animated Classics", question: "What city is Big Hero 6 set in?", answers: ["San Francisco", "Tokyo", "San Fransokyo", "New York"], correct: 2 },
  { category: "Animated Classics", question: "In Zootopia, what is Judy Hopps' profession?", answers: ["Detective", "Police Officer", "Mayor", "Lawyer"], correct: 1 },

  // More Pixar
  { category: "Pixar", question: "What is the name of the cleaning robot in WALL-E?", answers: ["WALL-E", "EVE", "M-O", "AUTO"], correct: 2 },
  { category: "Pixar", question: "In Finding Nemo, what is the address where Nemo is taken?", answers: ["42 Wallaby Way, Sydney", "42 Wallaby Street, Sydney", "43 Wallaby Way, Sydney", "44 Wallaby Way, Sydney"], correct: 0 },
  { category: "Pixar", question: "What is the name of Andy's neighbor who destroys toys in Toy Story?", answers: ["Sid Phillips", "Sid Johnson", "Sam Phillips", "Steve Phillips"], correct: 0 },
  { category: "Pixar", question: "In Monsters, Inc., what do monsters use children's screams for?", answers: ["Fun", "Power", "Money", "Food"], correct: 1 },
  { category: "Pixar", question: "What is the name of Carl's wife in Up?", answers: ["Ellen", "Ellie", "Emily", "Emma"], correct: 1 },
  { category: "Pixar", question: "In Ratatouille, what is the name of the restaurant?", answers: ["Gusteau's", "Le Ratatouille", "La Ratatouille", "Chez Remy"], correct: 0 },
  { category: "Pixar", question: "What is the name of the daycare toy who betrays the gang in Toy Story 3?", answers: ["Big Baby", "Lotso", "Ken", "Chuckles"], correct: 1 },
  { category: "Pixar", question: "In Inside Out, which emotion is not one of the five main ones?", answers: ["Joy", "Sadness", "Love", "Anger"], correct: 2 },
  { category: "Pixar", question: "What is Lightning McQueen's racing number?", answers: ["86", "95", "51", "43"], correct: 1 },
  { category: "Pixar", question: "In A Bug's Life, what do the ants gather for the grasshoppers?", answers: ["Food", "Water", "Leaves", "Seeds"], correct: 0 },
  { category: "Pixar", question: "What is the name of the villain in Toy Story 4?", answers: ["Gabby Gabby", "Duke Caboom", "Forky", "Bo Peep"], correct: 0 },
  { category: "Pixar", question: "In Onward, what are the main characters trying to bring back?", answers: ["Their mother", "Their father", "Their brother", "Their pet"], correct: 1 },
  { category: "Pixar", question: "What is the name of the sea monster town in Luca?", answers: ["Portorosso", "Portofino", "Portobello", "Porto"], correct: 0 },
  { category: "Pixar", question: "In Soul, what is the name of the place before life?", answers: ["The Before", "The Great Before", "The Beginning", "The Start"], correct: 1 },
  { category: "Pixar", question: "What instrument does Joe Gardner play in Soul?", answers: ["Saxophone", "Piano", "Trumpet", "Guitar"], correct: 1 },
  { category: "Pixar", question: "In Toy Story, what pizza place do the toys go to?", answers: ["Pizza Planet", "Planet Pizza", "Pizza World", "Pizza Place"], correct: 0 },
  { category: "Pixar", question: "What is the name of the sea turtle in Finding Nemo?", answers: ["Crush", "Squirt", "Dude", "Totally"], correct: 0 },
  { category: "Pixar", question: "In The Incredibles, what is Mr. Incredible's alter ego name?", answers: ["Bob Parr", "Robert Parr", "Both A and B", "Mr. Parr"], correct: 2 },
  { category: "Pixar", question: "What is the name of the volcano goddess in Luca?", answers: ["There is no volcano goddess", "Giulia", "Machiavelli", "Massimo"], correct: 0 },
  { category: "Pixar", question: "In Brave, what is the name of Merida's kingdom?", answers: ["DunBroch", "Scotland", "Highlands", "Camelot"], correct: 0 },

  // More Live Action
  { category: "Live Action", question: "In The Chronicles of Narnia, who is the White Witch?", answers: ["Jadis", "Susan", "Lucy", "Aslan"], correct: 0 },
  { category: "Live Action", question: "What is the name of the main character in Holes?", answers: ["Stanley Yelnats", "Zero", "X-Ray", "Squid"], correct: 0 },
  { category: "Live Action", question: "In National Treasure, what is the treasure hunter's name?", answers: ["Benjamin Franklin Gates", "Ben Gates", "Nicholas Cage", "Riley Poole"], correct: 1 },
  { category: "Live Action", question: "What is the name of the witch in Hocus Pocus who rides a vacuum?", answers: ["Winifred", "Sarah", "Mary", "Binx"], correct: 2 },
  { category: "Live Action", question: "In Tomorrowland, what object gives access to the futuristic city?", answers: ["A key", "A pin", "A watch", "A ring"], correct: 1 },
  { category: "Live Action", question: "What is the dog's name in The Shaggy Dog?", answers: ["Shaggy", "Wilby", "Khyi Yang Po", "The dog has no name"], correct: 2 },
  { category: "Live Action", question: "In Bedknobs and Broomsticks, what is Miss Price?", answers: ["A witch", "A teacher", "A nanny", "A governess"], correct: 0 },
  { category: "Live Action", question: "What sport is featured in The Rookie?", answers: ["Football", "Baseball", "Basketball", "Hockey"], correct: 1 },
  { category: "Live Action", question: "In A Wrinkle in Time, what is the main character's name?", answers: ["Meg Murry", "Charles Wallace", "Calvin", "IT"], correct: 0 },
  { category: "Live Action", question: "What is the name of the genie in the live-action Aladdin?", answers: ["Genie", "Robin", "Will", "He has no name"], correct: 3 },

  // More Theme Parks
  { category: "Theme Parks", question: "What is the name of the pirate in the Pirates of the Caribbean ride?", answers: ["Captain Jack Sparrow", "Davy Jones", "Multiple pirates", "Blackbeard"], correct: 2 },
  { category: "Theme Parks", question: "Which attraction is in all Disney castle parks?", answers: ["Space Mountain", "Dumbo", "It's a Small World", "All of the above"], correct: 3 },
  { category: "Theme Parks", question: "What is the fastest ride at Walt Disney World?", answers: ["Space Mountain", "Test Track", "Rock 'n' Roller Coaster", "Expedition Everest"], correct: 1 },
  { category: "Theme Parks", question: "In which land is Big Thunder Mountain Railroad located?", answers: ["Frontierland", "Adventureland", "Tomorrowland", "Fantasyland"], correct: 0 },
  { category: "Theme Parks", question: "What year did Disney's Animal Kingdom open?", answers: ["1996", "1998", "2000", "2002"], correct: 1 },
  { category: "Theme Parks", question: "Which park has the shortest height?", answers: ["Magic Kingdom", "Epcot", "Hollywood Studios", "Animal Kingdom"], correct: 2 },
  { category: "Theme Parks", question: "What is the name of the interactive game in Toy Story Land?", answers: ["Toy Story Mania", "Toy Story Midway Mania", "Slinky Dog Dash", "Alien Swirling Saucers"], correct: 1 },
  { category: "Theme Parks", question: "Which Disney park has a Matterhorn?", answers: ["Disneyland", "Walt Disney World", "Disneyland Paris", "Tokyo Disneyland"], correct: 0 },
  { category: "Theme Parks", question: "What is the name of the railroad at Disneyland?", answers: ["Disneyland Railroad", "Main Street Railroad", "Disney Railroad", "Walt's Railroad"], correct: 0 },
  { category: "Theme Parks", question: "In which park is the Tower of Terror?", answers: ["Magic Kingdom", "Epcot", "Hollywood Studios", "All Disney parks"], correct: 2 },

  // More Disney+/Marvel/Star Wars
  { category: "Disney+/Marvel/Star Wars", question: "What is the Mandalorian's real name?", answers: ["Din Djarin", "Boba Fett", "Jango Fett", "Paz Vizsla"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "In What If...?, who becomes Captain Carter?", answers: ["Sharon Carter", "Peggy Carter", "Hayley Atwell", "Agent 13"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the town in Agatha All Along?", answers: ["Westview", "Eastview", "Salem", "No specific town"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "In Echo, what is Maya Lopez's ability?", answers: ["Super strength", "Photographic reflexes", "Invisibility", "Telekinesis"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of America Chavez's power?", answers: ["Super strength", "Multiverse travel", "Flying", "Time travel"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In The Clone Wars, who is Anakin's padawan?", answers: ["Ahsoka Tano", "Obi-Wan Kenobi", "Barriss Offee", "Aayla Secura"], correct: 0 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the AI in Iron Man?", answers: ["JARVIS", "FRIDAY", "EDITH", "All of the above"], correct: 3 },
  { category: "Disney+/Marvel/Star Wars", question: "In Star Wars Rebels, who is the main character?", answers: ["Kanan Jarrus", "Ezra Bridger", "Hera Syndulla", "Sabine Wren"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "What is the name of the Winter Soldier's real identity?", answers: ["Steve Rogers", "Bucky Barnes", "Sam Wilson", "John Walker"], correct: 1 },
  { category: "Disney+/Marvel/Star Wars", question: "In Visions, what is unique about the series?", answers: ["Animated by different studios", "Japanese anime style", "Non-canon stories", "All of the above"], correct: 3 },

  // More Music
  { category: "Music", question: "What song does Ariel sing about wanting to be human?", answers: ["Part of Your World", "Under the Sea", "Kiss the Girl", "Poor Unfortunate Souls"], correct: 0 },
  { category: "Music", question: "In Encanto, what song does Luisa sing?", answers: ["Surface Pressure", "What Else Can I Do", "We Don't Talk About Bruno", "The Family Madrigal"], correct: 0 },
  { category: "Music", question: "Who sings 'How Far I'll Go' in Moana?", answers: ["Alessia Cara", "Auli'i Cravalho", "Dwayne Johnson", "Lin-Manuel Miranda"], correct: 1 },
  { category: "Music", question: "What is the love song in The Little Mermaid?", answers: ["Part of Your World", "Kiss the Girl", "Under the Sea", "Poor Unfortunate Souls"], correct: 1 },
  { category: "Music", question: "In Frozen 2, what song does Elsa sing while discovering her past?", answers: ["Into the Unknown", "Show Yourself", "The Next Right Thing", "All Is Found"], correct: 1 },
  { category: "Music", question: "What song do the toys sing in Toy Story?", answers: ["You've Got a Friend in Me", "Strange Things", "I Will Go Sailing No More", "None"], correct: 3 },
  { category: "Music", question: "Who composed the music for The Lion King?", answers: ["Hans Zimmer", "Elton John", "Tim Rice", "All of the above"], correct: 3 },
  { category: "Music", question: "In The Princess and the Frog, what song does Tiana sing about her dream?", answers: ["Down in New Orleans", "Almost There", "Dig a Little Deeper", "Friends on the Other Side"], correct: 1 },
  { category: "Music", question: "What is the opening song of Beauty and the Beast called?", answers: ["Belle", "Beauty and the Beast", "Prologue", "Once Upon a Time"], correct: 0 },
  { category: "Music", question: "In Mulan, who sings 'I'll Make a Man Out of You'?", answers: ["Li Shang", "Donny Osmond", "Jackie Chan", "Both A and B"], correct: 3 },

  // More Characters
  { category: "Characters", question: "What is the name of the cowgirl in Toy Story 2?", answers: ["Jessie", "Bo Peep", "Barbie", "Mrs. Potato Head"], correct: 0 },
  { category: "Characters", question: "Who is the Grand Councilwoman in Lilo & Stitch?", answers: ["Lilo", "Nani", "The alien leader", "Jumba"], correct: 2 },
  { category: "Characters", question: "What is the name of Moana's grandmother?", answers: ["Tala", "Sina", "Tui", "Gramma Tala"], correct: 3 },
  { category: "Characters", question: "In Ratatouille, what is the name of the food critic?", answers: ["Anton Ego", "Skinner", "Gusteau", "Colette"], correct: 0 },
  { category: "Characters", question: "What are the names of Hades' minions in Hercules?", answers: ["Pain and Panic", "Fear and Loathing", "Hurt and Havoc", "Chaos and Mayhem"], correct: 0 },
  { category: "Characters", question: "Who is the fashion designer in The Incredibles?", answers: ["Edna Mode", "Mirage", "Elastigirl", "Syndrome"], correct: 0 },
  { category: "Characters", question: "What is the name of the chef in The Little Mermaid?", answers: ["Louis", "Chef Louis", "Sebastian", "Grimsby"], correct: 1 },
  { category: "Characters", question: "In Frozen, who is the ice harvester?", answers: ["Hans", "Kristoff", "Olaf", "Sven"], correct: 1 },
  { category: "Characters", question: "What is the name of Pocahontas's raccoon friend?", answers: ["Meeko", "Flit", "Percy", "Nakoma"], correct: 0 },
  { category: "Characters", question: "Who is the villain's henchman in Sleeping Beauty?", answers: ["Diablo the raven", "Maleficent's goons", "Both A and B", "Prince Phillip"], correct: 2 },

  // More Villains
  { category: "Villains", question: "What is the name of the villain in Bolt?", answers: ["Dr. Calico", "Penny", "Mittens", "Rhino"], correct: 0 },
  { category: "Villains", question: "Who is the antagonist in Cars?", answers: ["Chick Hicks", "Doc Hudson", "Lightning McQueen", "The King"], correct: 0 },
  { category: "Villains", question: "In Peter Pan, what is Captain Hook's first mate?", answers: ["Smee", "Starkey", "Mullins", "Jukes"], correct: 0 },
  { category: "Villains", question: "What is the name of the villain in Toy Story 2?", answers: ["Al McWhiggin", "Stinky Pete", "Both", "Zurg"], correct: 2 },
  { category: "Villains", question: "Who is the main antagonist in Brave?", answers: ["Mor'du", "The Witch", "The Lords", "King Fergus"], correct: 0 },
  { category: "Villains", question: "What is Yzma's henchman's name in The Emperor's New Groove?", answers: ["Kronk", "Kuzco", "Pacha", "Tipo"], correct: 0 },
  { category: "Villains", question: "In The Lion King 2, who is the main villain?", answers: ["Zira", "Scar", "Nuka", "Kovu"], correct: 0 },
  { category: "Villains", question: "What is the name of the villain in Coco?", answers: ["Ernesto de la Cruz", "Hector", "The clerk", "Imelda"], correct: 0 },
  { category: "Villains", question: "Who is the antagonist in Ralph Breaks the Internet?", answers: ["Arthur", "Double Dan", "The virus", "All of the above"], correct: 2 },
  { category: "Villains", question: "In The Little Mermaid 2, who is the villain?", answers: ["Ursula", "Morgana", "Undertow", "Flotsam and Jetsam"], correct: 1 },

  // Walt Disney & History
  { category: "Characters", question: "What was Walt Disney's middle name?", answers: ["Walter", "Elias", "Roy", "Disney"], correct: 1 },
  { category: "Animated Classics", question: "What was Disney's first full-length animated feature?", answers: ["Pinocchio", "Snow White and the Seven Dwarfs", "Fantasia", "Bambi"], correct: 1 },
  { category: "Characters", question: "What character was Walt Disney's favorite?", answers: ["Mickey Mouse", "Donald Duck", "Goofy", "All equally"], correct: 0 },
  { category: "Theme Parks", question: "Where was Walt Disney born?", answers: ["California", "Florida", "Illinois", "Missouri"], correct: 2 },
  { category: "Animated Classics", question: "What was the first Disney film to use CGI?", answers: ["The Little Mermaid", "Beauty and the Beast", "The Black Cauldron", "Tron"], correct: 2 },
  { category: "Characters", question: "What was Mickey Mouse's first spoken words?", answers: ["Hot dog", "Oh boy", "Hiya", "Gosh"], correct: 0 },
  { category: "Animated Classics", question: "Which Disney film was the first to be nominated for Best Picture?", answers: ["Pinocchio", "Beauty and the Beast", "The Lion King", "Up"], correct: 1 },
  { category: "Characters", question: "What was Goofy's original name?", answers: ["Dippy Dawg", "Goofy", "Pluto", "Max"], correct: 0 },
  { category: "Animated Classics", question: "What Disney movie has the most songs?", answers: ["The Lion King", "Frozen", "Alice in Wonderland", "Beauty and the Beast"], correct: 2 },
  { category: "Animated Classics", question: "Which Disney princess has the least amount of screen time?", answers: ["Aurora", "Snow White", "Jasmine", "Pocahontas"], correct: 0 },
];
